function doc_paths = write_step11_7_docs(result_dir, keypoints, stage1_summary, stage2_summary, stage3_summary, stage4_summary, stage5_summary)
%WRITE_STEP11_7_DOCS Write Step11.7 Markdown reports.

names = {'00_STEP11_7_ONE_PAGE_SUMMARY.md','01_FINAL_BACKEND_INTERFACE.md','02_FINAL_ROUTE_FLOW.md', ...
    '03_CACHED_DIRECT_CONSISTENCY.md','04_FRONTEND_BIAS_AND_OOS_HANDLING.md','05_CACHE_FALLBACK_AND_RUNTIME.md', ...
    '06_LIMITATIONS_AND_USAGE_BOUNDARY.md','07_THESIS_WRITING_TEXT.md'};
doc_paths = cell(numel(names), 1);
for idx = 1:numel(names)
    doc_paths{idx} = fullfile(result_dir, names{idx});
end
write_text_local(doc_paths{1}, one_page_local(keypoints));
write_text_local(doc_paths{2}, interface_local());
write_text_local(doc_paths{3}, flow_local());
write_text_local(doc_paths{4}, consistency_local(stage2_summary));
write_text_local(doc_paths{5}, bias_oos_local(stage1_summary, stage3_summary));
write_text_local(doc_paths{6}, fallback_runtime_local(stage4_summary, stage5_summary));
write_text_local(doc_paths{7}, limitations_local());
write_text_local(doc_paths{8}, thesis_local());
end

function txt = one_page_local(k)
txt = sprintf(['# Step11.7 One-Page Summary\n\n', ...
    'Method position: final integration wrapper for the Step11 beamspace ML backend, not a new algorithm.\n\n', ...
    'Final chain: frontend-like local Y_work -> validate local state -> greedy_combined_B7 W -> Step11.6 canonical G cache -> Z=W''Y -> cached Step11.5 C05 -> estimate/confidence/boundary/cache/runtime diagnostics.\n\n', ...
    'Key pass metrics: interface=%d, cached_direct=%d, frontend_bias=%d, cache_fallback=%d, runtime=%d, overall=%d.\n\n', ...
    'Consistency: same_estimate=%.6f, same_policy=%.6f, same_score=%.6f, max_score_diff_rel=%.3g, cache_miss=%.0f.\n\n', ...
    'Final recommendation: `%s`.\n'], ...
    k.interface_smoke_pass_flag, k.cached_direct_consistency_pass_flag, k.frontend_prior_bias_recheck_pass_flag, ...
    k.cache_fallback_behavior_pass_flag, k.runtime_packaging_pass_flag, k.step11_7_overall_pass_flag, ...
    k.same_estimate_rate, k.same_policy_rate, k.same_score_rate, k.max_score_diff_rel, k.cache_miss_count, k.step11_7_recommendation);
end

function txt = interface_local()
txt = ['# Final Backend Interface', newline, newline, ...
    'Function: `out = step11_7_final_cached_c05_beamspace_ml_backend(input, context, opts)`.', newline, newline, ...
    'Input fields: `Y_work`, `frontend_state`, `coarseAz`, `coarseEl`, `rangeIdx`, `dopplerIdx`, `selectedCenterColumn`, `selectedCenterAz`, `method_tag`.', newline, newline, ...
    'Context fields: `cfg`, `arrInfo` or `geometry`, `W`, `w_info`, `cache`, `cache_metadata`, `manifold_opts`, `search_opts`, `C05_policy_cfg`, `full_search_cfg`, `coarse_search_cfg`, `base_refine_cfg`, `lambda`, `phase_factor`, `phase_sign`.', newline, newline, ...
    'Opts fields: `use_cache`, `run_direct_reference`, `allow_cache_fallback`, optional `truth_for_eval`, and `runtime_timing`.', newline, newline, ...
    'Output fields include status, route/method names, cache/fallback flags, confidence, boundary flag, az/el estimates, C05 policy/window fields, pair counts, runtime, input/Z shapes, debug, and error message.', newline, newline, ...
    'Unsupported frontend states return `out_of_scope` with low confidence and do not run high-confidence ML.', newline];
end

function txt = flow_local()
txt = ['# Final Route Flow', newline, newline, ...
    '1. Receive frontend-like local input and shared-center local observation `Y_work`.', newline, ...
    '2. Validate `frontend_state`, selected center, and `Y_work` shape. Reshape `65x32xT` to `N_elements x T` when needed.', newline, ...
    '3. Use fixed `greedy_combined_B7` W and fixed C05 policy.', newline, ...
    '4. Validate Step11.6 cache metadata and exact-grid coverage.', newline, ...
    '5. Build `Z = W''Y_work`.', newline, ...
    '6. Run cached C05 pair2d beamspace ML, with direct fallback only when explicitly allowed and recorded.', newline, ...
    '7. Return estimate, confidence, boundary/cache/runtime/debug fields.', newline, newline, ...
    'Pseudocode:', newline, newline, ...
    '```matlab', newline, ...
    'v = validate_step11_7_backend_input(input, context);', newline, ...
    'Z = context.W'' * v.Y;', newline, ...
    'out = cached_c05_search(Z, context.cache, input.coarseAz, input.coarseEl);', newline, ...
    '```', newline];
end

function txt = consistency_local(T)
txt = sprintf(['# Cached Direct Consistency\n\n', ...
    'Trials: %.0f.\n\nSame estimate rate: %.6f.\n\nSame policy rate: %.6f.\n\nSame score rate: %.6f.\n\nMax score diff rel: %.3g.\n\nCache miss count: %.0f.\n\nPass flag: %.0f.\n\nMismatch table: see CSV trial rows where `pass_flag=0`.\n'], ...
    T.num_trials(1), T.same_estimate_rate(1), T.same_policy_rate(1), T.same_score_rate(1), ...
    T.max_score_diff_rel(1), T.cache_miss_count(1), T.cached_direct_consistency_pass_flag(1));
end

function txt = bias_oos_local(stage1, stage3)
txt = sprintf(['# Frontend Bias And OOS Handling\n\n', ...
    'Bias cases: [0,0], [+0.20,0], [-0.20,0], [0,+0.20], [0,-0.20], [+0.20,+0.20], [-0.20,-0.20].\n\n', ...
    'Max topK miss rate: %.6f.\n\nMax boundary hit rate: %.6f.\n\nMax success drop vs zero: %.6f.\n\nHigh confidence misuse count: %.0f.\n\nInterface smoke pass: %.0f.\n\nOut-of-scope cases return low confidence or out_of_scope; no high-confidence override is allowed.\n'], ...
    stage3.max_topK_miss_rate(1), stage3.max_boundary_hit_rate(1), stage3.max_success_drop_vs_zero(1), ...
    stage3.high_confidence_misuse_count(1), stage1.interface_smoke_pass_flag(1));
end

function txt = fallback_runtime_local(stage4, stage5)
txt = sprintf(['# Cache Fallback And Runtime\n\n', ...
    'Cache miss/mismatch cases are explicitly recorded. Missing or mismatched cache metadata falls back to direct precompute only when `allow_cache_fallback=true`.\n\n', ...
    'Fallback behavior pass: %.0f.\n\nFallback expected case pass rate: %.6f.\n\nMedian final-route runtime reduction: %.6f.\n\nRuntime packaging pass: %.0f.\n\nMATLAB caveat: total runtime includes function dispatch and DML scoring; functional correctness is not invalidated if total MATLAB runtime gain is limited.\n'], ...
    stage4.cache_fallback_behavior_pass_flag(1), stage4.fallback_expected_case_pass_rate(1), ...
    stage5.median_runtime_reduction_ratio(1), stage5.runtime_packaging_pass_flag(1));
end

function txt = limitations_local()
txt = ['# Limitations And Usage Boundary', newline, newline, ...
    'Step11.7 is not the full LFM, pulse compression, MTD, or CFAR frontend chain.', newline, newline, ...
    'It is not a new ML model, does not change C05, does not redesign W, and does not change the controlled pair2d beamspace ML score.', newline, newline, ...
    'Lookup is exact-grid only. Interpolation is not part of the default route.', newline, newline, ...
    'The shared-center canonical local order is required, and cache metadata must match W method, canonical order, lookup mode, and interpolation flag.', newline, newline, ...
    'Full-field arbitrary multi-target search and fixed-point FPGA implementation are not claimed here.', newline];
end

function txt = thesis_local()
txt = ['# Thesis Writing Text', newline, newline, ...
    'If overall pass = 1 and runtime pass = 1:', newline, ...
    '本文最终将 Step11.5 的 C05 自适应搜索预算策略与 Step11.6 的 shared-center canonical beamspace manifold cache 封装为统一的 Step11.7 波束级 ML 后端。该后端在不改变 controlled pair2d beamspace ML 评分函数、不改变 W、不改变 C05 policy 的前提下，接收局部 Y_work 与前端粗中心信息，自动构造 beamspace 观测、执行 cached C05 搜索并输出角度估计、置信度、边界状态与运行诊断。实验表明，cached final backend 与 direct C05 backend 在估计结果、policy、score 和安全指标上保持一致，同时获得最终路径级运行时间下降。因此 Step11.7 可作为本文最终 Step11 波束级 ML 工程入口。', newline, newline, ...
    'If overall pass = 1 but runtime pass = 0:', newline, ...
    '本文最终将 Step11.5 C05 与 Step11.6 canonical cache 封装为统一 Step11.7 波束级 ML 后端。实验表明，该后端在功能上与 direct C05 完全一致，并具备清晰的输入输出、cache fallback 和 out-of-scope 处理机制；但 MATLAB 原型总运行时间收益受函数调度和 DML scoring 开销影响，不单独声称显著总 runtime 加速。该后端仍作为最终功能入口保留，runtime 优化留待 FPGA/SoC 实现阶段进一步验证。', newline, newline, ...
    'If overall pass = 0:', newline, ...
    '本文尝试将 Step11.5 C05 与 Step11.6 cache 封装为统一最终后端，但当前接口一致性、cache fallback 或 out-of-scope 处理尚未完全闭合。因此本文暂不采用 Step11.7 作为最终默认入口，而保留 Step11.5 与 Step11.6 的独立验证结论。', newline];
end

function write_text_local(path, text)
fid = fopen(path, 'w', 'n', 'UTF-8');
if fid < 0
    error('write_step11_7_docs:OpenFailed', 'Could not open %s.', path);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '%s', text);
clear cleanup;
end
