function doc_paths = write_step11_5_stage3_docs(result_dir, keypoints, alt_summary_table, repeat_summary_table, branch_trial_table, branch_summary_table)
%WRITE_STEP11_5_STAGE3_DOCS Write Stage3 required enhancement Markdown files.

if nargin < 6
    error('write_step11_5_stage3_docs:NotEnoughInputs', ...
        'result_dir, keypoints, alt_summary_table, repeat_summary_table, branch_trial_table, and branch_summary_table are required.');
end
if exist(result_dir, 'dir') ~= 7
    mkdir(result_dir);
end
doc_paths = {};
doc_paths{end + 1} = write_text_local(fullfile(result_dir, '00_STEP11_5_STAGE3_ONE_PAGE_SUMMARY.md'), one_page_local(keypoints));
doc_paths{end + 1} = write_text_local(fullfile(result_dir, '01_ALTERNATIVE_SPLIT_RECHECK.md'), alt_split_local(keypoints, alt_summary_table));
doc_paths{end + 1} = write_text_local(fullfile(result_dir, '02_REPEAT_SEED_METKL_RECHECK.md'), repeat_seed_local(keypoints, repeat_summary_table));
doc_paths{end + 1} = write_text_local(fullfile(result_dir, '03_TARGETED_BRANCH_RECHECK.md'), targeted_branch_local(keypoints, branch_trial_table, branch_summary_table));
doc_paths{end + 1} = write_text_local(fullfile(result_dir, '04_STAGE2_TO_STAGE3_CONCLUSION.md'), conclusion_local(keypoints));
doc_paths{end + 1} = write_text_local(fullfile(result_dir, '05_THESIS_WRITING_TEXT.md'), thesis_local(keypoints));
end

function text = one_page_local(k)
text = strjoin({ ...
    '# Step11.5 Stage3 One-Page Summary', ...
    '', ...
    '## Positioning', ...
    '', ...
    'Step11.5 Stage3 is a required enhancement validation of the Stage2 selected C05 policy. It is not Step11.6, not a new algorithm, and not a new C01-C12 tuning scan.', ...
    '', ...
    '## Preserved Stage1 and Stage2 conclusions', ...
    '', ...
    sprintf('- Stage1 label: `%s`', k.stage1_result_label), ...
    sprintf('- Stage2 selected_config_name = `%s`', k.selected_config_name), ...
    sprintf('- Stage2 stage2_adaptive_pass_flag = %.0f', k.stage2_adaptive_pass_flag), ...
    sprintf('- Stage2 recommended_next_step = `%s`', k.recommended_next_step), ...
    sprintf('- Stage2 validation pair_count_ratio = %.12g', k.validation_pair_count_ratio), ...
    sprintf('- Stage2 selected overall pair_count_ratio = %.12g', k.stage2_selected_pair_count_ratio), ...
    sprintf('- Stage2 bias robustness pass = %.0f, range = `%s`', k.bias_robustness_pass_flag, k.valid_bias_range_text), ...
    '', ...
    '## Stage3 required checks', ...
    '', ...
    sprintf('- alternative split recheck pass = %.0f', k.alt_split_recheck_pass_flag), ...
    sprintf('- repeat-seed larger-Metkl recheck pass = %.0f', k.repeat_seed_metkl_recheck_pass_flag), ...
    sprintf('- targeted branch recheck pass = %.0f', k.targeted_branch_recheck_pass_flag), ...
    sprintf('- Stage3 required enhancement pass = %.0f', k.stage3_required_enhancement_pass_flag), ...
    sprintf('- Stage3 recommended_next_step = `%s`', k.stage3_recommended_next_step) ...
    }, newline);
end

function text = alt_split_local(k, alt_summary_table)
val = alt_summary_table(strcmp(alt_summary_table.summary_scope, 'split_scheme_split') & ...
    strcmp(alt_summary_table.split_name, 'validation'), :);
text = strjoin({ ...
    '# Alternative Split Recheck', ...
    '', ...
    '## Purpose', ...
    '', ...
    'This check fixes Stage2 selected C05 and reruns the zero-bias representative trials under alternative validation splits. It verifies that the positive C05 conclusion is not only an odd/even trial_id split artifact.', ...
    '', ...
    '## Split schemes', ...
    '', ...
    '- `alt_mod3_validation`: validation uses trial_id divisible by 3.', ...
    '- `alt_tail_block_validation`: validation uses the last 40 percent of trial_id values.', ...
    '', ...
    '## Key metrics', ...
    '', ...
    sprintf('- validation schemes = %.12g', k.alt_split_num_validation_schemes), ...
    sprintf('- min adaptive success = %.12g', k.alt_split_min_adaptive_success), ...
    sprintf('- max adaptive RMSE = %.12g', k.alt_split_max_adaptive_rmse), ...
    sprintf('- max pair count ratio = %.12g', k.alt_split_max_pair_count_ratio), ...
    sprintf('- min full-grid match rate = %.12g', k.alt_split_min_full_grid_match_rate), ...
    sprintf('- max topK miss rate = %.12g', k.alt_split_max_topK_miss_rate), ...
    sprintf('- max boundary hit rate = %.12g', k.alt_split_max_boundary_hit_rate), ...
    sprintf('- max policy degeneracy flag = %.12g', k.alt_split_max_policy_degeneracy_flag), ...
    sprintf('- alt_split_recheck_pass_flag = %.0f', k.alt_split_recheck_pass_flag), ...
    '', ...
    '## Validation summary rows', ...
    '', ...
    table_to_markdown_local(val) ...
    }, newline);
end

function text = repeat_seed_local(k, repeat_summary_table)
seed_rows = repeat_summary_table(strcmp(repeat_summary_table.summary_scope, 'seed_group_all'), :);
overall = repeat_summary_table(strcmp(repeat_summary_table.summary_scope, 'overall'), :);
text = strjoin({ ...
    '# Repeat-Seed Larger-Metkl Recheck', ...
    '', ...
    '## Purpose', ...
    '', ...
    'This check fixes Stage2 selected C05 and reruns the representative scenarios with larger Metkl and repeated deterministic seed groups. It verifies that C05 is not a small Metkl=10 or single-seed artifact.', ...
    '', ...
    '## Key metrics', ...
    '', ...
    sprintf('- seed groups = %.12g', k.repeat_seed_num_seed_groups), ...
    sprintf('- Metkl per seed group = %.12g', k.repeat_seed_metkl_per_seed), ...
    sprintf('- min adaptive success = %.12g', k.repeat_seed_min_adaptive_success), ...
    sprintf('- max adaptive RMSE = %.12g', k.repeat_seed_max_adaptive_rmse), ...
    sprintf('- max pair count ratio = %.12g', k.repeat_seed_max_pair_count_ratio), ...
    sprintf('- min full-grid match rate = %.12g', k.repeat_seed_min_full_grid_match_rate), ...
    sprintf('- max topK miss rate = %.12g', k.repeat_seed_max_topK_miss_rate), ...
    sprintf('- max boundary hit rate = %.12g', k.repeat_seed_max_boundary_hit_rate), ...
    sprintf('- max policy degeneracy flag = %.12g', k.repeat_seed_max_policy_degeneracy_flag), ...
    sprintf('- repeat_seed_metkl_recheck_pass_flag = %.0f', k.repeat_seed_metkl_recheck_pass_flag), ...
    '', ...
    '## Seed-group summary rows', ...
    '', ...
    table_to_markdown_local(seed_rows), ...
    '', ...
    '## Overall summary', ...
    '', ...
    table_to_markdown_local(overall) ...
    }, newline);
end

function text = targeted_branch_local(k, branch_trial_table, branch_summary_table)
text = strjoin({ ...
    '# Targeted Branch Recheck', ...
    '', ...
    '## Purpose', ...
    '', ...
    'This check fixes Stage2 selected C05 and targets the v2 policy branches that were not naturally populated in Stage2 representative trials. The purpose is branch behavior and safe output validation, not high success under stress.', ...
    '', ...
    '## Branch criteria', ...
    '', ...
    '- BOUNDARY must be triggerable by real-search boundary stress and must not output high confidence.', ...
    '- ILL_CONDITIONED must be triggerable by real-search stress or deterministic policy guard probe and must output low confidence with unit windows.', ...
    '- A triggered safety branch is considered reasonable only when it avoids high-confidence misuse.', ...
    '', ...
    '## Key metrics', ...
    '', ...
    sprintf('- boundary_real_trigger_count = %.12g', k.boundary_real_trigger_count), ...
    sprintf('- ill_conditioned_real_trigger_count = %.12g', k.ill_conditioned_real_trigger_count), ...
    sprintf('- ill_conditioned_policy_probe_trigger_count = %.12g', k.ill_conditioned_policy_probe_trigger_count), ...
    sprintf('- high_confidence_misuse_rate = %.12g', k.targeted_branch_high_confidence_misuse_rate), ...
    sprintf('- targeted_branch_recheck_pass_flag = %.0f', k.targeted_branch_recheck_pass_flag), ...
    '', ...
    '## Branch trial rows', ...
    '', ...
    table_to_markdown_local(branch_trial_table), ...
    '', ...
    '## Branch summary rows', ...
    '', ...
    table_to_markdown_local(branch_summary_table) ...
    }, newline);
end

function text = conclusion_local(k)
if k.stage3_required_enhancement_pass_flag == 1
    conclusion = 'Stage3 supports keeping Stage2 selected C05 as the Step11.5 positive adaptive enhancement.';
else
    conclusion = 'Stage3 found at least one failed or limited enhancement check. Keep the Stage2 positive result but document the Stage3 boundary explicitly.';
end
text = strjoin({ ...
    '# Stage2 To Stage3 Conclusion', ...
    '', ...
    'Stage3 does not reselect policy parameters and does not modify Step11.1, Step11.2, Step11.3, or Step11.4. It validates only the already selected Stage2 C05 policy.', ...
    '', ...
    conclusion, ...
    '', ...
    sprintf('stage3_required_enhancement_pass_flag = %.0f', k.stage3_required_enhancement_pass_flag), ...
    sprintf('stage3_recommended_next_step = `%s`', k.stage3_recommended_next_step) ...
    }, newline);
end

function text = thesis_local(k)
if k.stage3_required_enhancement_pass_flag == 1
    para = ['Step11.5 Stage3 further validated the Stage2 selected C05 adaptive policy by testing alternative data splits, ', ...
        'larger Metkl with repeated seeds, and targeted safety-branch behavior. The alternative split and repeat-seed checks kept the same fixed C05 parameters and did not use target truth in search-center, candidate, topK, or policy decisions. ', ...
        'The targeted branch checks showed that BOUNDARY and ILL_CONDITIONED branches can be triggered and produce non-high-confidence safety outputs. ', ...
        'Therefore the Stage2 C05 policy can be retained as a positive adaptive enhancement after the Step11.3 fixed topK3 beamspace ML baseline.'];
else
    para = ['Step11.5 Stage3 kept the Stage2 selected C05 policy fixed and ran the required robustness and safety-branch rechecks. ', ...
        'At least one Stage3 check did not fully pass, so the Stage2 positive result should be reported together with the failed or limited Stage3 boundary condition.'];
end
text = strjoin({ ...
    '# Step11.5 Stage3 Thesis Writing Text', ...
    '', ...
    para ...
    }, newline);
end

function path = write_text_local(path, text)
fid = fopen(path, 'w', 'n', 'UTF-8');
if fid < 0
    error('write_step11_5_stage3_docs:OpenFailed', 'Could not open %s.', path);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '%s\n', text);
clear cleanup;
end

function text = table_to_markdown_local(T)
if isempty(T)
    text = '_No rows._';
    return;
end
vars = T.Properties.VariableNames;
lines = cell(height(T) + 2, 1);
lines{1} = ['| ', strjoin(vars, ' | '), ' |'];
lines{2} = ['| ', strjoin(repmat({'---'}, 1, numel(vars)), ' | '), ' |'];
for iRow = 1:height(T)
    parts = cell(1, numel(vars));
    for iVar = 1:numel(vars)
        parts{iVar} = value_to_text_local(T.(vars{iVar})(iRow));
    end
    lines{iRow + 2} = ['| ', strjoin(parts, ' | '), ' |'];
end
text = strjoin(lines, newline);
end

function text = value_to_text_local(value)
if iscell(value)
    text = char(value{1});
elseif isstring(value)
    text = char(value);
elseif islogical(value)
    text = sprintf('%d', value);
elseif isnumeric(value)
    text = sprintf('%.12g', value);
else
    text = char(value);
end
end
