function doc_paths = write_step11_5_stage2_docs(result_dir, keypoints, config_summary_table, policy_summary_table, bias_summary_table)
%WRITE_STEP11_5_STAGE2_DOCS Write Stage2 policy tuning Markdown package.

if nargin < 5
    error('write_step11_5_stage2_docs:NotEnoughInputs', ...
        'result_dir, keypoints, config_summary_table, policy_summary_table, and bias_summary_table are required.');
end
if exist(result_dir, 'dir') ~= 7
    mkdir(result_dir);
end
doc_paths = {};
doc_paths{end + 1} = write_text_local(fullfile(result_dir, '00_STEP11_5_STAGE2_ONE_PAGE_SUMMARY.md'), one_page_local(keypoints));
doc_paths{end + 1} = write_text_local(fullfile(result_dir, '01_POLICY_TUNING_THEORY.md'), theory_local());
doc_paths{end + 1} = write_text_local(fullfile(result_dir, '02_POLICY_TUNING_FLOW.md'), flow_local());
doc_paths{end + 1} = write_text_local(fullfile(result_dir, '03_POLICY_TUNING_RESULTS.md'), results_local(keypoints, config_summary_table, policy_summary_table, bias_summary_table));
doc_paths{end + 1} = write_text_local(fullfile(result_dir, '04_STAGE1_TO_STAGE2_COMPARISON.md'), comparison_local(keypoints));
doc_paths{end + 1} = write_text_local(fullfile(result_dir, '05_LIMITATIONS_AND_FINAL_RECOMMENDATION.md'), limitations_local(keypoints));
doc_paths{end + 1} = write_text_local(fullfile(result_dir, '06_THESIS_WRITING_TEXT.md'), thesis_local(keypoints));
end

function text = one_page_local(k)
text = strjoin({ ...
    '# Step11.5 Stage2 One-Page Summary', ...
    '', ...
    '## Stage label', ...
    '', ...
    'Step11.5 Stage2: calibrated search-budget policy tuning', ...
    '', ...
    '## Stage1 preserved result', ...
    '', ...
    k.stage1_result_label, ...
    '', ...
    sprintf('- Stage1 fixed_topK3_mean_num_pairs = %.12g', k.stage1_fixed_topK3_mean_num_pairs), ...
    sprintf('- Stage1 adaptive_mean_num_pairs = %.12g', k.stage1_adaptive_mean_num_pairs), ...
    '- Stage1 adaptive safety passed, but complexity failed because all samples entered HARD policy.', ...
    '', ...
    '## Stage2 diagnosis', ...
    '', ...
    'Stage1 failed because `H_norm` was near 1 and `gap_13` was smaller than the original 0.02 calibration scale. This pushed `U` above 0.55 for nearly every sample, so the policy became 100% HARD with topK=5 and 1.5x local windows.', ...
    '', ...
    '## Stage2 modification', ...
    '', ...
    'Stage2 decouples `U_search` from `U_confidence`. `H_norm` and `cond_risk` no longer dominate search budget; boundary risk controls window expansion, score gap controls topK growth, and fixed topK3 is the NORMAL default.', ...
    '', ...
    '## Selected recommendation', ...
    '', ...
    sprintf('- selected_config_name = `%s`', k.selected_config_name), ...
    sprintf('- selection_reason = `%s`', k.selection_reason), ...
    sprintf('- stage2_adaptive_pass_flag = %.0f', k.stage2_adaptive_pass_flag), ...
    sprintf('- recommended_next_step = `%s`', k.recommended_next_step), ...
    '', ...
    '## Validation metrics', ...
    '', ...
    sprintf('- validation_fixed_success = %.12g', k.validation_fixed_success), ...
    sprintf('- validation_adaptive_success = %.12g', k.validation_adaptive_success), ...
    sprintf('- validation_fixed_rmse = %.12g', k.validation_fixed_rmse), ...
    sprintf('- validation_adaptive_rmse = %.12g', k.validation_adaptive_rmse), ...
    sprintf('- validation_fixed_mean_num_pairs = %.12g', k.validation_fixed_mean_num_pairs), ...
    sprintf('- validation_adaptive_mean_num_pairs = %.12g', k.validation_adaptive_mean_num_pairs), ...
    sprintf('- validation_pair_count_ratio = %.12g', k.validation_pair_count_ratio), ...
    sprintf('- validation_policy_degeneracy_flag = %.12g', k.validation_policy_degeneracy_flag), ...
    '', ...
    '## Bias robustness', ...
    '', ...
    sprintf('- bias_robustness_pass_flag = %.0f', k.bias_robustness_pass_flag), ...
    sprintf('- valid_bias_range_text = `%s`', k.valid_bias_range_text) ...
    }, newline);
end

function text = theory_local()
text = strjoin({ ...
    '# Step11.5 Stage2 Policy Tuning Theory', ...
    '', ...
    'Stage2 keeps the Step11.3 controlled pair2d beamspace ML score unchanged:', ...
    '', ...
    '`J(Theta) = trace(P_G(Theta) Z Z'')`', ...
    '', ...
    'The corrected theory is not a new ML backend. It is a calibration of search-budget policy.', ...
    '', ...
    '## Stage1 failure diagnosis', ...
    '', ...
    '`H_norm` high means the coarse top candidates have similar likelihood scores, but it does not necessarily mean fixed topK3 will fail. `cond_risk` high means the beamspace pair manifold is ill-conditioned, but it should primarily affect confidence or boundary flags rather than force wider search. Boundary risk is the main reason to expand local refine windows. Small score gap can justify larger topK, but it should not automatically enlarge windows.', ...
    '', ...
    '## Decoupled uncertainties', ...
    '', ...
    '`gap_risk = 1 - min(gap_13 / gap_scale, 1)`', ...
    '', ...
    '`U_search = 0.65 gap_risk + 0.30 boundary_risk + 0.05 min(H_norm, 0.5)`', ...
    '', ...
    '`U_confidence = 0.35 H_norm + 0.25 gap_risk + 0.25 cond_risk + 0.15 boundary_risk`', ...
    '', ...
    'Both values are clipped to `[0, 1]`. `cond_risk` is not allowed to enter `U_search`, and entropy contributes at most 0.025 to `U_search`.', ...
    '', ...
    '## Policy rules', ...
    '', ...
    '- EASY: boundary free, not ill-conditioned, and `gap_13 >= easy_gap_threshold`; save compute with smaller topK/window.', ...
    '- NORMAL: default fixed topK3-equivalent search.', ...
    '- SCORE_AMBIGUOUS: small gap without boundary risk; increase topK only and keep window scale 1.00.', ...
    '- BOUNDARY: boundary risk; allow bounded window expansion with scale at most 1.25.', ...
    '- ILL_CONDITIONED: low confidence only; keep topK=3 and window scale 1.00.' ...
    }, newline);
end

function text = flow_local()
text = strjoin({ ...
    '# Step11.5 Stage2 Policy Tuning Flow', ...
    '', ...
    '1. Load fixed Step11.2 `greedy_combined_B7` and Step11.3 degree-based search helpers.', ...
    '2. Build the explicit C01-C12 policy tuning config table.', ...
    '3. For zero-bias representative trials, run full fine, fixed topK3, and adaptive v2 for every config.', ...
    '4. Split deterministically: odd `trial_id` is calibration and even `trial_id` is validation.', ...
    '5. Select the config on calibration split only. It must satisfy safety constraints and non-degenerate policy distribution.', ...
    '6. Evaluate final `stage2_adaptive_pass_flag` on validation split only.', ...
    '7. Run the selected config on required bias cases.', ...
    '8. Write independent Stage2 CSV/MAT/PNG/Markdown outputs without overwriting Stage1 results.', ...
    '', ...
    '## Pseudocode', ...
    '', ...
    '```text', ...
    'for each zero-bias trial:', ...
    '    compute full fine baseline', ...
    '    compute fixed topK3 baseline', ...
    '    compute coarse top7 candidates once', ...
    '    for each config C01-C12:', ...
    '        compute features_v2', ...
    '        select policy_v2', ...
    '        run Step11.3 local refine with v2 topK/window', ...
    'select config using calibration split only', ...
    'compute pass/fail using validation split only', ...
    'run selected config on bias cases', ...
    '```' ...
    }, newline);
end

function text = results_local(k, config_summary_table, policy_summary_table, bias_summary_table)
text = strjoin({ ...
    '# Step11.5 Stage2 Policy Tuning Results', ...
    '', ...
    '## Selected config', ...
    '', ...
    sprintf('- selected_config_name = `%s`', k.selected_config_name), ...
    sprintf('- stage2_adaptive_pass_flag = %.0f', k.stage2_adaptive_pass_flag), ...
    sprintf('- recommended_next_step = `%s`', k.recommended_next_step), ...
    '', ...
    '## Calibration split', ...
    '', ...
    sprintf('- fixed_success = %.12g', k.calibration_fixed_success), ...
    sprintf('- adaptive_success = %.12g', k.calibration_adaptive_success), ...
    sprintf('- fixed_rmse = %.12g', k.calibration_fixed_rmse), ...
    sprintf('- adaptive_rmse = %.12g', k.calibration_adaptive_rmse), ...
    sprintf('- fixed_mean_num_pairs = %.12g', k.calibration_fixed_mean_num_pairs), ...
    sprintf('- adaptive_mean_num_pairs = %.12g', k.calibration_adaptive_mean_num_pairs), ...
    sprintf('- pair_count_ratio = %.12g', k.calibration_pair_count_ratio), ...
    sprintf('- policy_degeneracy_flag = %.12g', k.calibration_policy_degeneracy_flag), ...
    '', ...
    '## Validation split', ...
    '', ...
    sprintf('- fixed_success = %.12g', k.validation_fixed_success), ...
    sprintf('- adaptive_success = %.12g', k.validation_adaptive_success), ...
    sprintf('- fixed_rmse = %.12g', k.validation_fixed_rmse), ...
    sprintf('- adaptive_rmse = %.12g', k.validation_adaptive_rmse), ...
    sprintf('- fixed_mean_num_pairs = %.12g', k.validation_fixed_mean_num_pairs), ...
    sprintf('- adaptive_mean_num_pairs = %.12g', k.validation_adaptive_mean_num_pairs), ...
    sprintf('- pair_count_ratio = %.12g', k.validation_pair_count_ratio), ...
    sprintf('- policy_degeneracy_flag = %.12g', k.validation_policy_degeneracy_flag), ...
    '', ...
    '## Config summary table', ...
    '', ...
    table_to_markdown_local(config_summary_table), ...
    '', ...
    '## Selected policy distribution', ...
    '', ...
    table_to_markdown_local(policy_summary_table), ...
    '', ...
    '## Bias robustness', ...
    '', ...
    table_to_markdown_local(bias_summary_table) ...
    }, newline);
end

function text = comparison_local(k)
text = strjoin({ ...
    '# Step11.5 Stage1 To Stage2 Comparison', ...
    '', ...
    '## Stage1', ...
    '', ...
    k.stage1_result_label, ...
    '', ...
    sprintf('- fixed_topK3_mean_num_pairs = %.12g', k.stage1_fixed_topK3_mean_num_pairs), ...
    sprintf('- stage1_adaptive_mean_num_pairs = %.12g', k.stage1_adaptive_mean_num_pairs), ...
    '- policy distribution: EASY=0, NORMAL=0, HARD=1, UNSAFE=0', ...
    '- conclusion: safety passed but complexity failed.', ...
    '', ...
    '## Stage2', ...
    '', ...
    sprintf('- selected_config_name = `%s`', k.selected_config_name), ...
    sprintf('- fixed_topK3_mean_num_pairs = %.12g', k.fixed_topK3_mean_num_pairs), ...
    sprintf('- stage2_selected_adaptive_mean_num_pairs = %.12g', k.stage2_selected_adaptive_mean_num_pairs), ...
    sprintf('- stage2_selected_pair_count_ratio = %.12g', k.stage2_selected_pair_count_ratio), ...
    sprintf('- stage2_adaptive_pass_flag = %.0f', k.stage2_adaptive_pass_flag), ...
    '', ...
    'Stage2 corrects the Stage1 over-conservative mapping by making fixed topK3 the NORMAL default and limiting window expansion to boundary-risk samples.' ...
    }, newline);
end

function text = limitations_local(k)
if k.stage2_adaptive_pass_flag == 1
    conclusion = 'Stage2 passes validation and can be treated as a positive adaptive enhancement after Step11.3 fixed topK3.';
else
    conclusion = 'Stage2 does not prove a stable validation-split complexity advantage. The final default engineering configuration remains Step11.3 fixed topK3.';
end
text = strjoin({ ...
    '# Step11.5 Stage2 Limitations And Final Recommendation', ...
    '', ...
    '1. Stage2 is still not a new ML score.', ...
    '2. Stage2 is not AP, full4D ML, or element-domain ML.', ...
    '3. Config selection uses calibration split only; pass/fail uses validation split only.', ...
    '4. Policy-degenerate configs are not allowed as positive adaptive results.', ...
    '5. Bias robustness is verified for the selected config only.', ...
    '6. Samples outside the verified bias range should enlarge windows or fall back to fixed/full fine search.', ...
    '', ...
    '## Final recommendation', ...
    '', ...
    conclusion, ...
    '', ...
    sprintf('recommended_next_step = `%s`', k.recommended_next_step) ...
    }, newline);
end

function text = thesis_local(k)
if k.stage2_adaptive_pass_flag == 1
    para = ['本文在 Step11.3 固定 topK3 粗到细 beamspace ML 搜索基础上，进一步提出一种经策略标定的似然地形感知自适应搜索预算分配方法。' ...
        '该方法将粗网格似然地形特征拆分为搜索预算不确定度和置信度不确定度，使 H_norm 与条件数风险主要用于置信输出，而将边界风险和 score gap 用于 topK/window 调整。' ...
        '实验表明，在保持 full-grid match、topK miss 和 boundary hit 不恶化的前提下，该方法较固定 topK3 进一步降低平均候选评分数量，可作为 controlled pair2d beamspace ML 的低复杂度增强策略。'];
elseif k.validation_safety_pass == 1
    para = ['本文进一步尝试了经重新标定的似然地形感知自适应搜索预算分配策略。实验表明，该策略在当前代表性场景下能够保持 fixed topK3 的成功率、RMSE、full-grid match、topK miss 与 boundary safety，' ...
        '但未在 validation split 上稳定取得平均候选数优势。因此最终默认工程配置仍采用 Step11.3 fixed topK3 coarse-to-fine beamspace ML 搜索，Step11.5 Stage2 作为自适应搜索策略的负结果和未来扩展依据保留。'];
else
    para = '本文尝试的自适应搜索预算策略在当前验证中未能同时保持 fixed topK3 的安全性和复杂度优势，因此不采用为默认方案。最终保留 Step11.3 fixed topK3 coarse-to-fine beamspace ML 作为工程默认配置。';
end
text = strjoin({ ...
    '# Step11.5 Stage2 Thesis Writing Text', ...
    '', ...
    para ...
    }, newline);
end

function path = write_text_local(path, text)
fid = fopen(path, 'w', 'n', 'UTF-8');
if fid < 0
    error('write_step11_5_stage2_docs:OpenFailed', 'Could not open %s.', path);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '%s\n', text);
clear cleanup;
end

function text = table_to_markdown_local(T)
if isempty(T)
    text = '_No rows._';
    return;
end
vars = T.Properties.VariableNames;
lines = cell(height(T) + 2, 1);
lines{1} = ['| ', strjoin(vars, ' | '), ' |'];
lines{2} = ['| ', strjoin(repmat({'---'}, 1, numel(vars)), ' | '), ' |'];
for iRow = 1:height(T)
    parts = cell(1, numel(vars));
    for iVar = 1:numel(vars)
        parts{iVar} = value_to_text_local(T.(vars{iVar})(iRow));
    end
    lines{iRow + 2} = ['| ', strjoin(parts, ' | '), ' |'];
end
text = strjoin(lines, newline);
end

function text = value_to_text_local(value)
if iscell(value)
    text = char(value{1});
elseif isstring(value)
    text = char(value);
elseif islogical(value)
    text = sprintf('%d', value);
elseif isnumeric(value)
    text = sprintf('%.12g', value);
else
    text = char(value);
end
end
