function doc_paths = write_step11_5_docs(result_dir, keypoints, trial_table, summary_table, policy_summary_table, bias_summary_table)
%WRITE_STEP11_5_DOCS Write Step11.5 Markdown evidence package.

if nargin < 6
    error('write_step11_5_docs:NotEnoughInputs', ...
        'result_dir, keypoints, trial_table, summary_table, policy_summary_table, and bias_summary_table are required.');
end
if exist(result_dir, 'dir') ~= 7
    mkdir(result_dir);
end

doc_paths = {};
doc_paths{end + 1} = write_text_local(fullfile(result_dir, '00_STEP11_5_ONE_PAGE_SUMMARY.md'), one_page_summary_local(keypoints));
doc_paths{end + 1} = write_text_local(fullfile(result_dir, '01_THEORY_AND_FORMULATION.md'), theory_doc_local());
doc_paths{end + 1} = write_text_local(fullfile(result_dir, '02_ALGORITHM_FLOW.md'), algorithm_flow_doc_local());
doc_paths{end + 1} = write_text_local(fullfile(result_dir, '03_EXPERIMENT_RESULTS.md'), experiment_doc_local(keypoints, summary_table, policy_summary_table, bias_summary_table));
doc_paths{end + 1} = write_text_local(fullfile(result_dir, '04_LIMITATIONS_AND_BOUNDARY.md'), limitations_doc_local());
doc_paths{end + 1} = write_text_local(fullfile(result_dir, '05_THESIS_WRITING_TEXT.md'), thesis_text_doc_local(keypoints));
unused = trial_table; %#ok<NASGU>
end

function text = one_page_summary_local(k)
text = strjoin({ ...
    '# Step11.5 One-Page Summary', ...
    '', ...
    '## Method name', ...
    '中文：基于似然地形不确定度的自适应 TopK-窗口波束级最大似然搜索方法', ...
    '', ...
    'English: Likelihood-Uncertainty-Aware Adaptive TopK-Window Beamspace ML Search', ...
    '', ...
    '## Positioning', ...
    'Step11.5 fixes the Step11.1 controlled pair2d beamspace DML score, fixes the Step11.2 greedy_combined_B7 beam matrix, and wraps the Step11.3 degree-based coarse-to-fine search with an uncertainty-aware adaptive topK/window budget allocator.', ...
    '', ...
    '## Algorithm inputs', ...
    '- Beamspace data: `Z = W''Y`.', ...
    '- Step11.3 coarse candidates from degree-based `el_sep_deg_list`.', ...
    '- Coarse likelihood scores, top-score gaps, boundary margin, and `cond(G''G + reg I)`.', ...
    '- Base Step11.3 refine settings: `topK=3`, local window `[0.32, 0.48] deg`, fine steps `[0.08, 0.12] deg`.', ...
    '', ...
    '## Adaptive policy table', ...
    '| Policy | Condition | adaptive_topK | window scale | confidence |', ...
    '|---|---:|---:|---:|---|', ...
    '| EASY | `U < 0.30`, no boundary risk, `cond_risk < 0.55` | 1 | 0.75 | high |', ...
    '| NORMAL | `0.30 <= U < 0.55`, no boundary risk | 3 | 1.00 | medium |', ...
    '| HARD | `0.55 <= U < 0.80` or boundary risk | 5 | 1.50 | medium_low |', ...
    '| UNSAFE | `U >= 0.80` or `cond_risk >= 0.85` | 7 | 2.00 | low |', ...
    '', ...
    '## Key metrics', ...
    sprintf('- full_fine_success = %.12g', k.full_fine_success), ...
    sprintf('- fixed_topK3_success = %.12g', k.fixed_topK3_success), ...
    sprintf('- adaptive_success = %.12g', k.adaptive_success), ...
    sprintf('- full_fine_rmse = %.12g', k.full_fine_rmse), ...
    sprintf('- fixed_topK3_rmse = %.12g', k.fixed_topK3_rmse), ...
    sprintf('- adaptive_rmse = %.12g', k.adaptive_rmse), ...
    sprintf('- full_fine_mean_num_pairs = %.12g', k.full_fine_mean_num_pairs), ...
    sprintf('- fixed_topK3_mean_num_pairs = %.12g', k.fixed_topK3_mean_num_pairs), ...
    sprintf('- adaptive_mean_num_pairs = %.12g', k.adaptive_mean_num_pairs), ...
    sprintf('- adaptive_full_grid_match_rate = %.12g', k.adaptive_full_grid_match_rate), ...
    sprintf('- adaptive_topK_miss_rate = %.12g', k.adaptive_topK_miss_rate), ...
    sprintf('- adaptive_boundary_hit_rate = %.12g', k.adaptive_boundary_hit_rate), ...
    '', ...
    '## Pass/fail conclusion', ...
    sprintf('- adaptive_pass_flag = %.0f', k.adaptive_pass_flag), ...
    sprintf('- recommended_next_step = `%s`', k.recommended_next_step), ...
    '', ...
    '## Usage boundary', ...
    'Low confidence and boundary flags are safety outputs, not new ML scores. Samples outside the verified bias range should enlarge the local window or fall back to fixed topK3/full fine search.' ...
    }, newline);
end

function text = theory_doc_local()
text = strjoin({ ...
    '# Step11.5 Theory And Formulation', ...
    '', ...
    '## Fixed beamspace DML model', ...
    '', ...
    '阵元域局部观测：', ...
    '', ...
    '`Y = A_cyl(Theta) S + N`', ...
    '', ...
    '波束域观测：', ...
    '', ...
    '`Z = W''Y`', ...
    '', ...
    '波束域流形：', ...
    '', ...
    '`G(Theta) = W'' A_cyl(Theta)`', ...
    '', ...
    '投影矩阵：', ...
    '', ...
    '`P_G(Theta) = G(Theta) [G(Theta)''G(Theta) + reg I]^(-1) G(Theta)''`', ...
    '', ...
    'DML 评分函数：', ...
    '', ...
    '`J(Theta) = trace(P_G(Theta) Z Z'')`', ...
    '', ...
    '其中 `Theta` 为 controlled pair2d 候选状态：', ...
    '', ...
    '`Theta = {az1, az2, el_center, el_sep_deg, orientation}`', ...
    '', ...
    '由 degree-based `el_sep_deg` 参数生成：', ...
    '', ...
    '`el1 = el_center - orientation * el_sep_deg / 2`', ...
    '', ...
    '`el2 = el_center + orientation * el_sep_deg / 2`', ...
    '', ...
    '`el_sep_deg` 是物理角度分离，不是 grid index difference。Step11.5 不修改上述 ML score。', ...
    '', ...
    '## Coarse likelihood-landscape uncertainty', ...
    '', ...
    '粗搜索阶段先使用 `topK_max = 7` 运行 Step11.3 degree-based coarse grid ML scoring，保留 top 7 coarse candidates:', ...
    '', ...
    '`C_i = {Theta_i, J_i}, i = 1,...,Kmax`, where `J_1 >= J_2 >= ... >= J_Kmax`.', ...
    '', ...
    '稳定归一化：', ...
    '', ...
    '`s_i = (J_i - J_1) / max(abs(J_1), eps)`', ...
    '', ...
    'max-shift softmax likelihood weights:', ...
    '', ...
    '`p_i = exp((s_i/tau) - max_k(s_k/tau)) / sum_k exp((s_k/tau) - max_k(s_k/tau))`', ...
    '', ...
    '默认 `tau = 0.02`。', ...
    '', ...
    '似然熵：', ...
    '', ...
    '`H_J = -sum_i p_i log(p_i + eps)`', ...
    '', ...
    '归一化熵：', ...
    '', ...
    '`H_norm = H_J / log(Kmax)`', ...
    '', ...
    'top-score gap:', ...
    '', ...
    '`gap_13 = (J_1 - J_3) / max(abs(J_1), eps)`', ...
    '', ...
    '`gap_17 = (J_1 - J_7) / max(abs(J_1), eps)`', ...
    '', ...
    '边界距离：', ...
    '', ...
    '`d_az = min(az1-az_min, az_max-az1, az2-az_min, az_max-az2)`', ...
    '', ...
    '`d_el = min(el_center-el_min, el_max-el_center)`', ...
    '', ...
    '`boundary_margin = min(d_az / max(coarse_az_step, eps), d_el / max(coarse_el_step, eps))`', ...
    '', ...
    '`boundary_risk = 1 if boundary_margin < 1.5 else 0`', ...
    '', ...
    '条件数风险：', ...
    '', ...
    '`kappa_G = cond(G_best''G_best + reg I)`', ...
    '', ...
    '`cond_risk = min(log10(kappa_G) / 8, 1)`', ...
    '', ...
    '综合不确定度：', ...
    '', ...
    '`U = 0.45 H_norm + 0.25 (1 - min(gap_13 / 0.02, 1)) + 0.15 boundary_risk + 0.15 cond_risk`', ...
    '', ...
    '`U` is clipped to `[0, 1]`.', ...
    '', ...
    '## Policy mapping', ...
    '', ...
    '- EASY: `U < 0.30`, `boundary_risk == 0`, `cond_risk < 0.55`; use `adaptive_topK = 1`, scale `0.75`, confidence high.', ...
    '- NORMAL: `0.30 <= U < 0.55`, `boundary_risk == 0`; use `adaptive_topK = 3`, scale `1.00`, confidence medium.', ...
    '- HARD: `0.55 <= U < 0.80` or `boundary_risk == 1`; use `adaptive_topK = 5`, scale `1.50`, confidence medium_low.', ...
    '- UNSAFE: `U >= 0.80` or `cond_risk >= 0.85`; use `adaptive_topK = 7`, scale `2.00`, confidence low and boundary flag `search_uncertain_or_ill_conditioned`.', ...
    '', ...
    'All policies still execute fine refine with the same Step11.3 controlled pair2d beamspace DML scoring function.' ...
    }, newline);
end

function text = algorithm_flow_doc_local()
text = strjoin({ ...
    '# Step11.5 Algorithm Flow', ...
    '', ...
    '## Text flow', ...
    '', ...
    '1. Build `Z = W''Y` with fixed `greedy_combined_B7`.', ...
    '2. Run Step11.3 degree-based coarse grid topK search with `topK_max = 7`.', ...
    '3. Compute coarse likelihood-landscape features: entropy, gaps, boundary risk, condition risk, and uncertainty `U`.', ...
    '4. Select EASY/NORMAL/HARD/UNSAFE deterministic policy.', ...
    '5. Retain only the prefix of the already sorted coarse top candidates.', ...
    '6. Scale Step11.3 base local half-widths and clamp windows to global local-search bounds.', ...
    '7. Run Step11.3 local refine from the retained topK candidates.', ...
    '8. Output best ML estimate plus confidence, boundary flag, feature, policy, and candidate-count debug fields.', ...
    '', ...
    '## Pseudocode', ...
    '', ...
    '```text', ...
    'input Z, W, array coordinates, lambda, coarse_cfg, base_refine_cfg', ...
    'top_candidates, coarse_debug = Step11.3.coarse_grid_topk(topK_max=7)', ...
    'features = compute_likelihood_landscape_features(top_candidates, coarse_debug)', ...
    'policy = select_adaptive_topk_window_policy(features, base_refine_cfg)', ...
    'selected = top_candidates[1:policy.adaptive_topK]', ...
    'adaptive_refine_cfg = scale(base_refine_cfg, policy.window_scale)', ...
    'est, refine_debug = Step11.3.local_refine_from_topk(selected, adaptive_refine_cfg)', ...
    'return est, features, policy, coarse_debug, refine_debug, num_pairs', ...
    '```', ...
    '', ...
    '## Input fields', ...
    '', ...
    '- `Z, W, x, y, z, lambda`: beamspace data and array geometry.', ...
    '- `grid_cfg_coarse`: degree-based coarse grid with `coarse_el_sep_deg_list = [0, 0.36, 0.72]`.', ...
    '- `base_refine_cfg`: Step11.3 base fine settings with `[0, 0.24, 0.36, 0.48, 0.60, 0.72]` fine elevation separations.', ...
    '- `manifold_opts`, `search_opts`: same phase and regularization options used by Step11.3.', ...
    '- `policy_cfg`: `topK_max = 7`, `tau = 0.02`.', ...
    '', ...
    '## Output fields', ...
    '', ...
    '- `est_adaptive`: `az_hat`, `el_hat`, `el_center_hat`, `el_sep_hat`, `orientation_hat`, and ML score.', ...
    '- `debug_adaptive.features`: `H_norm`, `gap_13`, `gap_17`, `boundary_margin`, `boundary_risk`, `cond_risk`, `U`, top scores, softmax weights.', ...
    '- `debug_adaptive.policy`: policy name, adaptive topK, scaled windows, confidence, boundary flag.', ...
    '- `debug_adaptive.num_pairs_total`: coarse plus adaptive-refine candidate count.', ...
    '- `debug_adaptive.failure_reason`: low-confidence failure text if all refine windows produce no candidate rows.' ...
    }, newline);
end

function text = experiment_doc_local(k, summary_table, policy_summary_table, bias_summary_table)
policy_lines = table_to_markdown_local(policy_summary_table);
bias_lines = table_to_markdown_local(bias_summary_table);
unused = summary_table; %#ok<NASGU>
text = strjoin({ ...
    '# Step11.5 Experiment Results', ...
    '', ...
    '## Full fine vs fixed topK3 vs adaptive comparison', ...
    '', ...
    sprintf('- full_fine_success = %.12g', k.full_fine_success), ...
    sprintf('- fixed_topK3_success = %.12g', k.fixed_topK3_success), ...
    sprintf('- adaptive_success = %.12g', k.adaptive_success), ...
    sprintf('- full_fine_rmse = %.12g', k.full_fine_rmse), ...
    sprintf('- fixed_topK3_rmse = %.12g', k.fixed_topK3_rmse), ...
    sprintf('- adaptive_rmse = %.12g', k.adaptive_rmse), ...
    sprintf('- full_fine_mean_num_pairs = %.12g', k.full_fine_mean_num_pairs), ...
    sprintf('- fixed_topK3_mean_num_pairs = %.12g', k.fixed_topK3_mean_num_pairs), ...
    sprintf('- adaptive_mean_num_pairs = %.12g', k.adaptive_mean_num_pairs), ...
    sprintf('- adaptive_vs_fixed_pair_count_ratio = %.12g', k.adaptive_vs_fixed_pair_count_ratio), ...
    sprintf('- adaptive_full_grid_match_rate = %.12g', k.adaptive_full_grid_match_rate), ...
    sprintf('- adaptive_topK_miss_rate = %.12g', k.adaptive_topK_miss_rate), ...
    sprintf('- adaptive_boundary_hit_rate = %.12g', k.adaptive_boundary_hit_rate), ...
    '', ...
    '## Policy distribution', ...
    '', ...
    policy_lines, ...
    '', ...
    '## Candidate count reduction', ...
    '', ...
    sprintf('Fixed topK3 reduction ratio is %.12g; adaptive reduction ratio is %.12g. The adaptive-vs-fixed reduction gain is %.12g.', ...
        k.fixed_topK3_reduction_ratio, k.adaptive_reduction_ratio, k.adaptive_vs_fixed_reduction_gain), ...
    '', ...
    '## RMSE/success comparison', ...
    '', ...
    sprintf('The adaptive pass flag is `%d`. Recommended next step: `%s`.', k.adaptive_pass_flag, k.recommended_next_step), ...
    '', ...
    '## Bias robustness', ...
    '', ...
    bias_lines, ...
    '', ...
    sprintf('- max_bias_adaptive_topK_miss_rate = %.12g', k.max_bias_adaptive_topK_miss_rate), ...
    sprintf('- max_bias_adaptive_boundary_hit_rate = %.12g', k.max_bias_adaptive_boundary_hit_rate), ...
    sprintf('- max_bias_adaptive_success_drop = %.12g', k.max_bias_adaptive_success_drop), ...
    sprintf('- valid_bias_range_text = `%s`', k.valid_bias_range_text) ...
    }, newline);
end

function text = limitations_doc_local()
text = strjoin({ ...
    '# Step11.5 Limitations And Boundary', ...
    '', ...
    '1. 本方法不是新的 ML score。Step11.5 只改变 coarse-to-fine 搜索预算分配，不改变 `J(Theta) = trace(P_G Z Z'')`。', ...
    '2. 本方法不是 AP。它不构造 AP 空间谱，也不采用 AP 判决。', ...
    '3. 本方法不是 element-domain ML。观测与搜索均保持 Step11.3 beamspace 形式。', ...
    '4. 本方法依赖前端粗中心在局部窗口内。若前端中心偏差超出局部窗口保护范围，应扩大窗口或回退。', ...
    '5. 本方法的自适应阈值只在当前 representative scenarios 验证。', ...
    '6. 对超出 bias range 的样本，必须扩大窗口或退回 fixed/full fine search。', ...
    '7. low confidence / boundary flag 不是算法失败，而是安全输出策略。' ...
    }, newline);
end

function text = thesis_text_doc_local(k)
if k.adaptive_pass_flag == 1
    recommendation = ['本文在固定 controlled pair2d beamspace ML 估计模型和固定 greedy_combined_B7 波束组合矩阵的基础上，' ...
        '进一步提出一种基于似然地形不确定度的自适应粗到细搜索加速方法。该方法利用粗网格 ML 分数熵、' ...
        'top-score margin、搜索边界距离和 beamspace 流形条件数对样本搜索难度进行判别，并据此自适应选择 topK 候选数与局部细搜索窗口尺度。' ...
        '相比固定 topK3 粗到细搜索，该方法在保持 full fine grid 匹配率、topK miss 和边界风险不恶化的前提下，' ...
        '进一步降低平均候选评分数量，实现了受控双目标波束级 ML 的低复杂度工程化增强。'];
else
    recommendation = ['本文进一步尝试了基于似然地形不确定度的自适应搜索预算分配策略。实验表明，该策略在当前代表性场景中保持了与固定 topK3 方案相近的安全性，' ...
        '但复杂度收益未超过固定 topK3 基线，因此最终默认工程配置仍采用 Step11.3 固定 topK3 粗到细 beamspace ML 搜索，' ...
        'Step11.5 作为自适应搜索策略的边界验证与未来扩展方向保留。'];
end

text = strjoin({ ...
    '# Step11.5 Thesis Writing Text', ...
    '', ...
    '## 方法介绍', ...
    '', ...
    '本文提出基于似然地形不确定度的自适应 TopK-窗口波束级最大似然搜索方法。该方法以 Step11.3 的 degree-based coarse-to-fine beamspace ML 为基线，在不改变 ML 评分函数和波束组合矩阵的前提下，根据粗搜索阶段的候选分数地形动态分配细搜索预算。', ...
    '', ...
    '## 理论建模', ...
    '', ...
    '阵元域观测写为 `Y = A_cyl(Theta)S + N`，波束域观测为 `Z = W''Y`，波束域流形为 `G(Theta) = W''A_cyl(Theta)`。对每个 controlled pair2d 候选状态，仍采用 `P_G = G(G''G+regI)^(-1)G''` 与 `J = trace(P_GZZ'')` 作为确定性 ML 评分。', ...
    '', ...
    '## 自适应搜索策略', ...
    '', ...
    '粗网格先保留 top 7 候选，通过归一化分数 softmax 权重计算似然熵，同时结合 `gap_13`、`gap_17`、边界距离和 `cond(G''G+regI)` 形成综合不确定度 `U`。根据 `U` 和风险项，样本被确定性地分配为 EASY、NORMAL、HARD 或 UNSAFE，并分别采用 topK=1/3/5/7 与 0.75/1.00/1.50/2.00 的局部窗口尺度。', ...
    '', ...
    '## 复杂度分析', ...
    '', ...
    sprintf('在代表性 zero-bias 场景中，full fine 平均候选数为 %.12g，固定 topK3 平均候选数为 %.12g，自适应方案平均候选数为 %.12g。固定 topK3 降低比例为 %.12g，自适应降低比例为 %.12g。', ...
        k.full_fine_mean_num_pairs, k.fixed_topK3_mean_num_pairs, k.adaptive_mean_num_pairs, ...
        k.fixed_topK3_reduction_ratio, k.adaptive_reduction_ratio), ...
    '', ...
    '## 实验结果描述', ...
    '', ...
    sprintf('自适应方法 success=%.12g、RMSE=%.12g、full-grid match rate=%.12g、topK miss rate=%.12g、boundary hit rate=%.12g，pass flag=%d。', ...
        k.adaptive_success, k.adaptive_rmse, k.adaptive_full_grid_match_rate, ...
        k.adaptive_topK_miss_rate, k.adaptive_boundary_hit_rate, k.adaptive_pass_flag), ...
    '', ...
    '## 与 Step11.3 fixed topK3 的区别', ...
    '', ...
    'Step11.3 使用固定 topK=3 和固定局部 refine window。Step11.5 不改变 Step11.3 的后端评分和 degree-based 候选定义，而是在粗搜索后增加可观测的似然地形不确定度判别，并据此自适应选择 topK 与窗口尺度。', ...
    '', ...
    '## 创新点表述', ...
    '', ...
    recommendation ...
    }, newline);
end

function path = write_text_local(path, text)
fid = fopen(path, 'w', 'n', 'UTF-8');
if fid < 0
    error('write_step11_5_docs:OpenFailed', 'Could not open %s.', path);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '%s\n', text);
clear cleanup;
end

function text = table_to_markdown_local(T)
if isempty(T)
    text = '_No rows._';
    return;
end
vars = T.Properties.VariableNames;
lines = cell(height(T) + 2, 1);
lines{1} = ['| ', strjoin(vars, ' | '), ' |'];
lines{2} = ['| ', strjoin(repmat({'---'}, 1, numel(vars)), ' | '), ' |'];
for iRow = 1:height(T)
    parts = cell(1, numel(vars));
    for iVar = 1:numel(vars)
        value = T.(vars{iVar})(iRow);
        parts{iVar} = value_to_text_local(value);
    end
    lines{iRow + 2} = ['| ', strjoin(parts, ' | '), ' |'];
end
text = strjoin(lines, newline);
end

function text = value_to_text_local(value)
if iscell(value)
    text = char(value{1});
elseif isstring(value)
    text = char(value);
elseif islogical(value)
    text = sprintf('%d', value);
elseif isnumeric(value)
    text = sprintf('%.12g', value);
else
    text = char(value);
end
end
