function doc_paths = write_step11_5_stage3_supplementary_docs(result_dir, keypoints, metkl_summary_table, ill_stress_table, ill_summary_table, guard_probe_table, final_recommendation_table)
%WRITE_STEP11_5_STAGE3_SUPPLEMENTARY_DOCS Write Stage3 supplementary Markdown documentation.

if nargin < 7
    error('write_step11_5_stage3_supplementary_docs:NotEnoughInputs', ...
        'result_dir, keypoints, summaries, guard probe, and final recommendation are required.');
end
if exist(result_dir, 'dir') ~= 7
    mkdir(result_dir);
end
doc_paths = {};
doc_paths{end + 1} = write_text_local(fullfile(result_dir, '00_STEP11_5_STAGE3_SUPP_ONE_PAGE_SUMMARY.md'), one_page_local(keypoints));
doc_paths{end + 1} = write_text_local(fullfile(result_dir, '01_METKL30_REPEAT_SEED_RECHECK.md'), metkl30_local(keypoints, metkl_summary_table));
doc_paths{end + 1} = write_text_local(fullfile(result_dir, '02_ILL_CONDITIONED_REAL_STRESS_RECHECK.md'), illcond_local(keypoints, ill_stress_table, ill_summary_table, guard_probe_table));
doc_paths{end + 1} = write_text_local(fullfile(result_dir, '03_FINAL_SUPPLEMENTARY_EVIDENCE.md'), final_evidence_local(keypoints, final_recommendation_table));
doc_paths{end + 1} = write_text_local(fullfile(result_dir, '04_THESIS_WRITING_TEXT.md'), thesis_text_local());
end

function text = one_page_local(k)
text = strjoin({ ...
    '# Step11.5 Stage3 Supplementary Rechecks One-Page Summary', ...
    '', ...
    '## Stage2 C05 recap', ...
    '', ...
    sprintf('- selected_config_name = `%s`', k.stage2_selected_config_name), ...
    sprintf('- stage2_adaptive_pass_flag = %.0f', k.stage2_adaptive_pass_flag), ...
    '', ...
    '## Stage3 required validation recap', ...
    '', ...
    sprintf('- stage3_required_enhancement_pass_flag = %.0f', k.stage3_required_enhancement_pass_flag), ...
    '', ...
    '## Metkl=30 repeat-seed result', ...
    '', ...
    sprintf('- seed groups = %.12g', k.metkl30_num_seed_groups), ...
    sprintf('- Metkl per seed = %.12g', k.metkl30_metkl_per_seed), ...
    sprintf('- total trials = %.12g', k.metkl30_total_trials), ...
    sprintf('- max pair count ratio = %.12g', k.metkl30_max_pair_count_ratio), ...
    sprintf('- max topK miss rate = %.12g', k.metkl30_max_topK_miss_rate), ...
    sprintf('- max boundary hit rate = %.12g', k.metkl30_max_boundary_hit_rate), ...
    sprintf('- metkl30_repeat_pass_flag = %.0f', k.metkl30_repeat_pass_flag), ...
    '', ...
    '## Ill-conditioned real-search stress result', ...
    '', ...
    sprintf('- total cases = %.12g', k.illcond_total_cases), ...
    sprintf('- total trials = %.12g', k.illcond_total_trials), ...
    sprintf('- real trigger count = %.12g', k.illcond_real_trigger_count), ...
    sprintf('- real trigger rate = %.12g', k.illcond_real_trigger_rate), ...
    sprintf('- high confidence misuse rate = %.12g', k.illcond_high_confidence_misuse_rate), ...
    sprintf('- real stress pass flag = %.0f', k.illcond_real_stress_pass_flag), ...
    sprintf('- guard probe pass flag = %.0f', k.illcond_guard_probe_pass_flag), ...
    sprintf('- real stress result = `%s`', k.illcond_real_stress_result_text), ...
    '', ...
    '## Final supplementary recommendation', ...
    '', ...
    sprintf('- stage3_supplementary_pass_flag = %.0f', k.stage3_supplementary_pass_flag), ...
    sprintf('- recommendation = `%s`', k.stage3_supplementary_recommendation) ...
    }, newline);
end

function text = metkl30_local(k, summary_table)
seed_rows = summary_table(strcmp(summary_table.summary_scope, 'seed_group'), :);
scenario_rows = summary_table(strcmp(summary_table.summary_scope, 'scenario'), :);
policy_rows = summary_table(strcmp(summary_table.summary_scope, 'policy'), :);
overall_rows = summary_table(strcmp(summary_table.summary_scope, 'overall'), :);
text = strjoin({ ...
    '# Metkl=30 Repeat-Seed Recheck', ...
    '', ...
    '## Setup', ...
    '', ...
    '- base_seed_list = `[20260609, 20260610, 20260611]`', ...
    '- Metkl = `30`', ...
    '- scenarios = `easy_noncoherent`, `strong_coherent`, `hard_phase`, `weak_secondary`, `low_snr_hard`', ...
    '- policy = fixed Stage2 selected `C05_easy_very_aggressive`', ...
    '', ...
    '## Pass/fail', ...
    '', ...
    sprintf('- metkl30_repeat_pass_flag = %.0f', k.metkl30_repeat_pass_flag), ...
    sprintf('- failed seed groups = `%s`', k.metkl30_failed_seed_group_text), ...
    sprintf('- max pair count ratio = %.12g', k.metkl30_max_pair_count_ratio), ...
    sprintf('- min full-grid match rate = %.12g', k.metkl30_min_full_grid_match_rate), ...
    '', ...
    '## Per seed group', ...
    '', ...
    table_to_markdown_local(seed_rows), ...
    '', ...
    '## Overall', ...
    '', ...
    table_to_markdown_local(overall_rows), ...
    '', ...
    '## Per scenario', ...
    '', ...
    table_to_markdown_local(scenario_rows), ...
    '', ...
    '## Per policy', ...
    '', ...
    table_to_markdown_local(policy_rows), ...
    '', ...
    '## Interpretation', ...
    '', ...
    metkl30_interpretation_local(k) ...
    }, newline);
end

function text = illcond_local(k, ill_stress_table, ill_summary_table, guard_probe_table)
case_table = unique(ill_stress_table(:, {'stress_group','stress_case_name','az_sep_deg','el_sep_deg','rho','phase_deg','beta','snr_db'}), 'rows', 'stable');
text = strjoin({ ...
    '# Ill-Conditioned Real-Search Stress Recheck', ...
    '', ...
    '## Purpose', ...
    '', ...
    'This recheck attempts to make the fixed C05 ILL_CONDITIONED branch trigger naturally in the real search pipeline. It does not lower `cond_threshold`, does not force policy labels, and does not use truth for policy decisions.', ...
    '', ...
    '## Stress case table', ...
    '', ...
    table_to_markdown_local(case_table), ...
    '', ...
    '## Summary', ...
    '', ...
    table_to_markdown_local(ill_summary_table), ...
    '', ...
    '## Guard probe', ...
    '', ...
    table_to_markdown_local(guard_probe_table), ...
    '', ...
    '## Key result', ...
    '', ...
    sprintf('- illcond_real_trigger_count = %.12g', k.illcond_real_trigger_count), ...
    sprintf('- illcond_real_trigger_rate = %.12g', k.illcond_real_trigger_rate), ...
    sprintf('- illcond_max_cond_risk = %.12g', k.illcond_max_cond_risk), ...
    sprintf('- illcond_max_cond_best_GHG = %.12g', k.illcond_max_cond_best_GHG), ...
    sprintf('- illcond_high_confidence_misuse_rate = %.12g', k.illcond_high_confidence_misuse_rate), ...
    sprintf('- illcond_real_stress_pass_flag = %.0f', k.illcond_real_stress_pass_flag), ...
    sprintf('- illcond_guard_probe_pass_flag = %.0f', k.illcond_guard_probe_pass_flag), ...
    sprintf('- result text = `%s`', k.illcond_real_stress_result_text), ...
    '', ...
    illcond_interpretation_local(k) ...
    }, newline);
end

function text = final_evidence_local(k, final_recommendation_table)
text = strjoin({ ...
    '# Final Supplementary Evidence', ...
    '', ...
    '## Final recommendation table', ...
    '', ...
    table_to_markdown_local(final_recommendation_table), ...
    '', ...
    '## Current thesis conclusion', ...
    '', ...
    final_conclusion_local(k), ...
    '', ...
    '## Boundary statement to preserve', ...
    '', ...
    boundary_statement_local(k) ...
    }, newline);
end

function text = thesis_text_local()
text = strjoin({ ...
    '# Step11.5 Stage3 Supplementary Thesis Writing Text', ...
    '', ...
    '## Case 1: Metkl30 passed and ill-conditioned real stress naturally triggered', ...
    '', ...
    '本文进一步对 Step11.5 Stage2 推荐的 C05 自适应搜索策略进行了 Metkl=30 多 seed 复验和更强 ill-conditioned real-search stress。结果表明，C05 不仅在代表性场景下稳定保持候选数优势与安全性，而且病态分支可在真实搜索压力样本中自然触发，并输出低置信安全状态。因此，Step11.5 C05 可作为 controlled pair2d beamspace ML 的最终自适应搜索增强策略。', ...
    '', ...
    '## Case 2: Metkl30 passed, ill-conditioned real stress did not naturally trigger, guard probe passed', ...
    '', ...
    '本文进一步对 Step11.5 Stage2 推荐的 C05 自适应搜索策略进行了 Metkl=30 多 seed 复验，结果表明该策略在更大样本和多个 seed group 下仍保持 fixed topK3 的安全性与候选数优势。针对 ill-conditioned 分支，真实搜索压力样本在当前固定 W、网格和阈值条件下未自然触发该分支，但 deterministic guard probe 验证了病态保护逻辑会输出低置信状态且不会造成高置信误用。因此，本文将 C05 作为代表性场景下的最终正向增强结果，同时将 ill-conditioned 真实触发作为边界分析和未来工作保留。', ...
    '', ...
    '## Case 3: Metkl30 did not pass', ...
    '', ...
    '本文进一步对 Step11.5 Stage2 推荐的 C05 自适应搜索策略进行了 Metkl=30 多 seed 复验，但结果未能稳定保持 fixed topK3 的安全性或候选数优势。因此，本文不进一步强化 Step11.5 C05 的最终主张，而保留已有 Stage3 required validation 结论，并将更大样本稳定性作为后续工作。' ...
    }, newline);
end

function text = metkl30_interpretation_local(k)
if k.metkl30_repeat_pass_flag == 1
    text = 'Metkl=30 repeat-seed evidence strengthens the Stage2/Stage3 C05 positive result under larger representative-scenario sampling.';
else
    text = 'Metkl=30 repeat-seed evidence does not strengthen the Stage2/Stage3 C05 claim. The failed seed group and metric should be reported.';
end
end

function text = illcond_interpretation_local(k)
if k.illcond_real_stress_pass_flag == 1
    text = 'ILL_CONDITIONED was naturally triggered in real-search stress and passed the confidence safety checks.';
elseif k.illcond_guard_probe_pass_flag == 1
    text = 'ILL_CONDITIONED was not naturally triggered in real-search stress under the current fixed C05/W/grid/threshold setting. The deterministic guard probe remains only logic evidence and must not be described as real-search triggering.';
else
    text = 'Neither real-search stress nor deterministic guard probe fully validated the ILL_CONDITIONED branch. This remains a boundary limitation.';
end
end

function text = final_conclusion_local(k)
if k.stage3_supplementary_pass_flag == 1
    text = 'The supplementary evidence supports strengthening C05 as the final Step11.5 adaptive enhancement with both larger-sample robustness and real ill-conditioned branch triggering.';
elseif k.metkl30_repeat_pass_flag == 1 && k.illcond_guard_probe_pass_flag == 1
    text = 'The supplementary evidence strengthens C05 on Metkl=30 representative-scenario robustness, while keeping real ill-conditioned triggering as boundary/future work.';
else
    text = 'The supplementary evidence does not strengthen the existing Stage3 required validation conclusion.';
end
end

function text = boundary_statement_local(k)
if k.illcond_real_trigger_count == 0
    text = 'Because ill-conditioned real-search stress did not naturally trigger ILL_CONDITIONED, the thesis must not claim real-search triggering. It may only claim deterministic guard-probe validation of the safety logic.';
else
    text = 'Ill-conditioned real-search triggering occurred in this supplementary stress set; still report that the stress is branch-behavior evidence rather than representative-scene success evidence.';
end
end

function path = write_text_local(path, text)
fid = fopen(path, 'w', 'n', 'UTF-8');
if fid < 0
    error('write_step11_5_stage3_supplementary_docs:OpenFailed', 'Could not open %s.', path);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '%s\n', text);
clear cleanup;
end

function text = table_to_markdown_local(T)
if isempty(T)
    text = '_No rows._';
    return;
end
vars = T.Properties.VariableNames;
lines = cell(height(T) + 2, 1);
lines{1} = ['| ', strjoin(vars, ' | '), ' |'];
lines{2} = ['| ', strjoin(repmat({'---'}, 1, numel(vars)), ' | '), ' |'];
for iRow = 1:height(T)
    parts = cell(1, numel(vars));
    for iVar = 1:numel(vars)
        parts{iVar} = value_to_text_local(T.(vars{iVar})(iRow));
    end
    lines{iRow + 2} = ['| ', strjoin(parts, ' | '), ' |'];
end
text = strjoin(lines, newline);
end

function text = value_to_text_local(value)
if iscell(value)
    text = char(value{1});
elseif isstring(value)
    text = char(value);
elseif islogical(value)
    text = sprintf('%d', value);
elseif isnumeric(value)
    text = sprintf('%.12g', value);
else
    text = char(value);
end
end
