clc
clear
close all

script_dir = fileparts(mfilename('fullpath'));
step_dir = fileparts(script_dir);
common_dir = fullfile(step_dir, 'common');
result_dir = fullfile(step_dir, 'results_step11_4_stage1_interface_contract');

addpath(common_dir);
if exist(result_dir, 'dir') ~= 7
    mkdir(result_dir);
end

log_lines = {};
log_lines = append_log_local(log_lines, 'Step11.4 Stage1 interface contract starts');
log_lines = append_log_local(log_lines, 'Script: %s', mfilename('fullpath'));
log_lines = append_log_local(log_lines, 'Result directory: %s', result_dir);

search_window = struct('az_half_width_deg', 1.5, 'el_half_width_deg', 1.2);
cluster_indicator = struct('beam_spread_indicator', 0.18, ...
    'local_peak_count', 1, 'cluster_score', 0.42);
quality = struct('snr_proxy_db', 25, 'observable_coarse_center', true);
truth_for_metrics = struct('az_pair_deg', [9.4, 10.6], ...
    'el_pair_deg', [4.8, 5.2], 'truth_not_used_for_coarse_center', true);
beam_energy = magic(5);

frontend_out = make_frontend_out_struct( ...
    'CoarseAzDeg', 10.0, ...
    'CoarseElDeg', 5.0, ...
    'SearchWindow', search_window, ...
    'BeamEnergy', beam_energy, ...
    'ClusterIndicator', cluster_indicator, ...
    'Method', 'stage1_contract_synthetic_observable_peak', ...
    'Quality', quality, ...
    'TruthForMetrics', truth_for_metrics);
backend_cfg = build_step11_backend_config_from_frontend(frontend_out);

N = 8;
L = 4;
B = 3;
rng(20260624, 'twister');
Y = randn(N, L) + 1j * randn(N, L);
W = randn(N, B) + 1j * randn(N, B);
backend_in = make_backend_in_from_frontend_out(frontend_out, Y, W, ...
    'BackendCfg', backend_cfg);

required_frontend_fields = {'interface_version','coarse_az_deg','coarse_el_deg', ...
    'coarse_center_deg','search_window','beam_energy','cluster_indicator','method', ...
    'quality','truth_for_metrics','truth_is_for_metrics_only'};
required_backend_fields = {'interface_version','Y','W','Z','coarse_center_deg', ...
    'backend_cfg','coarse_grid_cfg','refine_cfg','manifold_opts','search_opts', ...
    'topK','metadata','backend_ready_flag'};

frontend_out_fields_ok = all(isfield(frontend_out, required_frontend_fields));
backend_in_fields_ok = all(isfield(backend_in, required_backend_fields));
backend_dimension_ok = isequal(size(backend_in.Z), [size(W, 2), size(Y, 2)]);
coarse_center_alignment_ok = all(abs(backend_in.coarse_center_deg - ...
    frontend_out.coarse_center_deg) < 1e-12);
truth_guard_ok = frontend_out.truth_is_for_metrics_only && ...
    backend_in.metadata.truth_not_used_for_coarse_center;
search_cfg_fields_ok = all(isfield(backend_in.backend_cfg, ...
    {'coarse_grid_cfg','refine_cfg','manifold_opts','search_opts','topK'}));
recommended_search_values_ok = backend_in.topK == 3 && ...
    abs(backend_in.coarse_grid_cfg.az_step - 0.16) < 1e-12 && ...
    abs(backend_in.coarse_grid_cfg.el_step - 0.24) < 1e-12 && ...
    abs(backend_in.refine_cfg.fine_az_step - 0.08) < 1e-12 && ...
    abs(backend_in.refine_cfg.fine_el_step - 0.12) < 1e-12;

interface_contract_pass_flag = frontend_out_fields_ok && backend_in_fields_ok && ...
    backend_dimension_ok && coarse_center_alignment_ok && truth_guard_ok && ...
    search_cfg_fields_ok && recommended_search_values_ok;

summary_table = table(frontend_out_fields_ok, backend_in_fields_ok, backend_dimension_ok, ...
    coarse_center_alignment_ok, truth_guard_ok, search_cfg_fields_ok, ...
    recommended_search_values_ok, interface_contract_pass_flag);

keypoint_names = {'frontend_out_fields_ok'; 'backend_in_fields_ok'; ...
    'backend_dimension_ok'; 'coarse_center_alignment_ok'; 'truth_guard_ok'; ...
    'search_cfg_fields_ok'; 'recommended_search_values_ok'; ...
    'interface_contract_pass_flag'; 'backend_topK'; ...
    'coarse_az_step'; 'coarse_el_step'; 'fine_az_step'; 'fine_el_step'};
keypoint_values = [frontend_out_fields_ok; backend_in_fields_ok; backend_dimension_ok; ...
    coarse_center_alignment_ok; truth_guard_ok; search_cfg_fields_ok; ...
    recommended_search_values_ok; interface_contract_pass_flag; backend_in.topK; ...
    backend_in.coarse_grid_cfg.az_step; backend_in.coarse_grid_cfg.el_step; ...
    backend_in.refine_cfg.fine_az_step; backend_in.refine_cfg.fine_el_step];
keypoint_table = table(string(keypoint_names), string(num2str(keypoint_values, '%.12g')), ...
    'VariableNames', {'keypoint','value'});

summary_csv = fullfile(result_dir, 'step11_4_stage1_summary.csv');
keypoints_csv = fullfile(result_dir, 'step11_4_stage1_keypoints.csv');
mat_path = fullfile(result_dir, 'step11_4_stage1_result.mat');
log_path = fullfile(result_dir, 'step11_4_stage1.log');
readme_path = fullfile(result_dir, 'README.md');

writetable(summary_table, summary_csv);
writetable(keypoint_table, keypoints_csv);
save(mat_path, 'frontend_out', 'backend_in', 'backend_cfg', 'summary_table', 'keypoint_table');

log_lines = append_log_local(log_lines, 'frontend_out_fields_ok = %d', frontend_out_fields_ok);
log_lines = append_log_local(log_lines, 'backend_in_fields_ok = %d', backend_in_fields_ok);
log_lines = append_log_local(log_lines, 'backend_dimension_ok = %d', backend_dimension_ok);
log_lines = append_log_local(log_lines, 'coarse_center_alignment_ok = %d', coarse_center_alignment_ok);
log_lines = append_log_local(log_lines, 'truth_guard_ok = %d', truth_guard_ok);
log_lines = append_log_local(log_lines, 'search_cfg_fields_ok = %d', search_cfg_fields_ok);
log_lines = append_log_local(log_lines, 'recommended_search_values_ok = %d', recommended_search_values_ok);
log_lines = append_log_local(log_lines, 'interface_contract_pass_flag = %d', interface_contract_pass_flag);
write_text_local(log_path, sprintf('%s\n', log_lines{:}));

status_lines = { ...
    '# Stage1 Interface Contract Status', ...
    '', ...
    sprintf('- frontend_out_fields_ok = %d', frontend_out_fields_ok), ...
    sprintf('- backend_in_fields_ok = %d', backend_in_fields_ok), ...
    sprintf('- interface_contract_pass_flag = %d', interface_contract_pass_flag), ...
    '', ...
    'Truth is carried only for offline metrics and is not used to build the frontend coarse center.'};
write_text_local(readme_path, sprintf('%s\n', status_lines{:}));

if ~interface_contract_pass_flag
    error('run_stage1_interface_contract:ContractFailed', 'Stage1 interface contract did not pass.');
end
fprintf('Stage1 interface contract passed. Results: %s\n', result_dir);

function write_text_local(path_now, text_now)
fid = fopen(path_now, 'w');
if fid < 0
    error('run_stage1_interface_contract:WriteFailed', 'Could not open file: %s', path_now);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '%s', text_now);
clear cleanup;
end
