function doc_paths = write_step11_1_final_docs(evidence, result_dir)
%WRITE_STEP11_1_FINAL_DOCS Write Stage7 final Markdown evidence documents.

if nargin ~= 2
    error('write_step11_1_final_docs:InvalidInputCount', 'evidence and result_dir are required.');
end
if ~exist(result_dir, 'dir')
    mkdir(result_dir);
end

doc_specs = { ...
    '00_FINAL_STEP11_1_ONE_PAGE_SUMMARY.md', @doc_one_page_local; ...
    '01_ALGORITHM_FORMULATION.md', @doc_formulation_local; ...
    '02_ALGORITHM_FLOW.md', @doc_flow_local; ...
    '03_EXPERIMENT_EVIDENCE_TABLES.md', @doc_evidence_tables_local; ...
    '04_COMPLEXITY_AND_BEAMSPACE_DIMENSION.md', @doc_complexity_local; ...
    '05_COMPARISON_WITH_STEP7_BEAM_SMOOTHING.md', @doc_step7_compare_local; ...
    '06_LIMITATIONS_AND_BOUNDARY_CASES.md', @doc_limitations_local; ...
    '07_THESIS_WRITING_OUTLINE.md', @doc_outline_local};

doc_paths = cell(size(doc_specs, 1), 1);
for idx = 1:size(doc_specs, 1)
    out_path = fullfile(result_dir, doc_specs{idx, 1});
    text = doc_specs{idx, 2}(evidence);
    write_text_local(out_path, text);
    doc_paths{idx} = out_path;
end
end

function text = doc_one_page_local(evidence)
stage_table = evidence.stage_status_table;
key_table = evidence.final_key_metrics_table;
stage_md = table_to_markdown_local(stage_table(:, {'stage','key_pass_flag','pass_flag_value','conclusion','limitation'}));
key_md = table_to_markdown_local(key_table);
text = join_lines_local({ ...
    '# Final Step11.1 One-Page Summary', ...
    '', ...
    '## Method Name', ...
    '', ...
    'Beam-level controlled-parameter maximum likelihood estimation for local unresolved two-target cylindrical-array scenes.', ...
    '', ...
    'Chinese thesis wording: 面向圆柱阵局部未分辨双目标的波束级受控参数最大似然估计方法。', ...
    '', ...
    '## One-Sentence Positioning', ...
    '', ...
    'Use the real cylindrical-array 3D manifold to build a low-dimensional beamspace manifold, then run controlled two-target DML search directly in beamspace.', ...
    '', ...
    '## Final Main Algorithm', ...
    '', ...
    '- Main route: controlled pair2d beamspace ML.', ...
    '- Baseline: common-el restricted beamspace ML.', ...
    '- Upper bound: local full4d beamspace ML.', ...
    '- Not AP and not an engineering confidence-boundary closure.', ...
    '', ...
    '## Stage Evidence', ...
    '', ...
    stage_md, ...
    '', ...
    '## Key Metrics', ...
    '', ...
    key_md, ...
    '', ...
    '## Final Recommendation', ...
    '', ...
    evidence.final_recommendation, ...
    '', ...
    '## Boundary Statement', ...
    '', ...
    'Stage5 reports worst-case joint success equal to 0 and max false-high-like risk equal to 1. These results must stay visible: the route is suitable as a thesis main ML route with boundary documentation, not as a claim that every strong-coherence case is solved.'});
end

function text = doc_formulation_local(~)
text = join_lines_local({ ...
    '# Algorithm Formulation', ...
    '', ...
    'The local cylindrical-array snapshot model is:', ...
    '', ...
    '```text', ...
    'Y = A_cyl(Theta) S + N', ...
    '```', ...
    '', ...
    'The beamspace observation is:', ...
    '', ...
    '```text', ...
    'Z = W''Y', ...
    '```', ...
    '', ...
    'The beamspace manifold is:', ...
    '', ...
    '```text', ...
    'G(Theta) = W''A_cyl(Theta)', ...
    '```', ...
    '', ...
    'The deterministic ML score is:', ...
    '', ...
    '```text', ...
    'J(Theta) = trace(P_G Z Z'')', ...
    'P_G = G(G''G)^(-1)G''', ...
    '```', ...
    '', ...
    '## Controlled Pair2D Parameterization', ...
    '', ...
    '```text', ...
    'az1 < az2', ...
    'el_center = (el1 + el2) / 2', ...
    'el_sep = |el2 - el1|', ...
    'orientation in {+1, -1}', ...
    '```', ...
    '', ...
    'This parameterization is lower-dimensional than full4d while retaining small separated-elevation modeling.', ...
    '', ...
    '## Full4D Upper-Bound Parameterization', ...
    '', ...
    '```text', ...
    'az1 < az2', ...
    'el1 arbitrary local grid value', ...
    'el2 arbitrary local grid value', ...
    '```', ...
    '', ...
    'Full4d is used as a local upper-bound comparison, not as the default final algorithm.'});
end

function text = doc_flow_local(~)
text = join_lines_local({ ...
    '# Algorithm Flow', ...
    '', ...
    '```text', ...
    'front-end coarse center', ...
    '  -> local cylindrical work subarray', ...
    '  -> local az/el beam matrix W', ...
    '  -> beamspace snapshots Z = W''Y', ...
    '  -> candidate models: common-el / controlled pair2d / full4d upper bound', ...
    '  -> beamspace DML score J(Theta)', ...
    '  -> two-target az/el estimate', ...
    '  -> boundary and limitation label', ...
    '```', ...
    '', ...
    'The main thesis route uses controlled pair2d. Common-el is the baseline and full4d is the upper-bound reference.'});
end

function text = doc_evidence_tables_local(evidence)
text = join_lines_local({ ...
    '# Experiment Evidence Tables', ...
    '', ...
    '## Stage Status', ...
    '', ...
    table_to_markdown_local(evidence.stage_status_table), ...
    '', ...
    '## Final Key Metrics', ...
    '', ...
    table_to_markdown_local(evidence.final_key_metrics_table), ...
    '', ...
    '## Missing Files', ...
    '', ...
    missing_files_markdown_local(evidence.missing_files)});
end

function text = doc_complexity_local(evidence)
[n_elem, pair_ratio] = complexity_values_local(evidence);
text = join_lines_local({ ...
    '# Complexity And Beamspace Dimension', ...
    '', ...
    sprintf('The active cylindrical work subarray has `N_elem = %.0f` elements.', n_elem), ...
    'Stage6 beam layouts use `B = 25` (`az5_el5`) or `B = 15` (`az5_el3`) beam channels, so the DML projection is evaluated in a much lower-dimensional beamspace.', ...
    '', ...
    'Candidate-count scaling:', ...
    '', ...
    '```text', ...
    'common-el          ~ C(N_az, 2) * N_el', ...
    'controlled pair2d  ~ C(N_az, 2) * N_el * N_sep * N_orientation_eff', ...
    'full4d             ~ C(N_az, 2) * N_el^2', ...
    '```', ...
    '', ...
    sprintf('In Stage6, the measured full4d/pair2d runtime proxy ratio is `%.6g`.', pair_ratio), ...
    '', ...
    'Since Stage6 reports no success-rate gap between full4d and controlled pair2d in the main comparison subset, controlled pair2d is the better complexity-performance default. Full4d remains useful as an upper-bound diagnostic or future small-window refinement.'});
end

function text = doc_step7_compare_local(~)
text = join_lines_local({ ...
    '# Comparison With Step7 Beam Smoothing', ...
    '', ...
    'Step7 beam-index smoothing MUSIC uses sliding windows over beam indices. The weakness is that beam-index windows do not provide the physical translation invariance that true array subarrays provide.', ...
    '', ...
    'Step11.1 does not use beam-index smoothing. It keeps the real cylindrical manifold and projects it into beamspace:', ...
    '', ...
    '```text', ...
    'G(Theta) = W''A_cyl(Theta)', ...
    '```', ...
    '', ...
    'Therefore the theoretical basis is different: Step11.1 evaluates physically parameterized cylindrical steering candidates in beamspace, instead of treating adjacent beam indices as a virtual shift-invariant array.'});
end

function text = doc_limitations_local(evidence)
[stage5_worst, false_high, full_role] = limitation_values_local(evidence);
text = join_lines_local({ ...
    '# Limitations And Boundary Cases', ...
    '', ...
    '- This route does not claim all strong-coherence scenarios succeed.', ...
    sprintf('- Stage5 worst-case pair2d-white joint success is `%.12g`.', stage5_worst), ...
    sprintf('- Stage5 max false-high-like risk proxy is `%.12g`.', false_high), ...
    '- Weak secondary targets, near anti-phase cases, and small angular separations remain boundary cases.', ...
    sprintf('- Stage6 full4d recommended role is `%s`.', full_role), ...
    '- Full4d is an upper-bound comparison, not the default main algorithm.', ...
    '- AP has not been validated in Step11.1.', ...
    '- Engineering confidence boundary and model selection are not complete.'});
end

function text = doc_outline_local(~)
text = join_lines_local({ ...
    '# Thesis Writing Outline', ...
    '', ...
    '1. Motivation for beam-level ML in local unresolved cylindrical-array two-target scenes.', ...
    '2. Limitations of beam-index smoothing and why physical manifold evaluation is needed.', ...
    '3. Cylindrical-array beamspace manifold construction with `Z = W''Y` and `G = W''A_cyl`.', ...
    '4. Controlled pair2d DML parameterization and scoring.', ...
    '5. Baselines and upper bounds: common-el and full4d.', ...
    '6. Experiment design from Stage1 to Stage6.', ...
    '7. Evidence summary: prior ablation, cylindrical migration, el separation, coherence stress, full4d comparison.', ...
    '8. Boundary cases and limitations.', ...
    '9. Final conclusion and future work: confidence boundary, optional AP, and small-window refinement.'});
end

function [n_elem, ratio] = complexity_values_local(evidence)
n_elem = 2080;
ratio = get_key_metric_value_local(evidence, 'Stage6 full4d upper-bound comparison', 'complexity_ratio_full4d_over_pair2d');
if ~isfinite(ratio)
    ratio = NaN;
end
end

function [stage5_worst, false_high, full_role] = limitation_values_local(evidence)
stage5_worst = get_key_metric_value_local(evidence, 'Stage5 coherence stress', 'worst_case_joint_success_pair2d_white');
false_high = get_key_metric_value_local(evidence, 'Stage5 coherence stress', 'max_false_high_like_rate');
full_role = get_key_metric_text_local(evidence, 'Stage6 full4d upper-bound comparison', 'full4d_recommended_role');
if isempty(full_role)
    full_role = 'unknown';
end
end

function value = get_key_metric_value_local(evidence, stage_name, metric)
tbl = evidence.final_key_metrics_table;
mask = strcmp(string(tbl.stage), string(stage_name)) & strcmp(string(tbl.metric), string(metric));
if any(mask)
    value = tbl.metric_value(find(mask, 1, 'first'));
else
    value = NaN;
end
end

function text = get_key_metric_text_local(evidence, stage_name, metric)
tbl = evidence.final_key_metrics_table;
mask = strcmp(string(tbl.stage), string(stage_name)) & strcmp(string(tbl.metric), string(metric));
if any(mask)
    text = char(tbl.metric_text(find(mask, 1, 'first')));
else
    text = '';
end
end

function md = table_to_markdown_local(tbl)
if isempty(tbl)
    md = '_No rows._';
    return;
end
names = tbl.Properties.VariableNames;
lines = cell(height(tbl) + 2, 1);
lines{1} = ['| ' strjoin(names, ' | ') ' |'];
lines{2} = ['| ' strjoin(repmat({'---'}, 1, numel(names)), ' | ') ' |'];
for iRow = 1:height(tbl)
    vals = cell(1, numel(names));
    for iCol = 1:numel(names)
        vals{iCol} = value_to_text_local(tbl.(names{iCol})(iRow));
    end
    lines{iRow + 2} = ['| ' strjoin(vals, ' | ') ' |'];
end
md = strjoin(lines, newline);
end

function text = value_to_text_local(value)
if iscell(value)
    text = char(value{1});
elseif isstring(value)
    text = char(value);
elseif isnumeric(value) || islogical(value)
    if isfinite(value)
        text = sprintf('%.12g', value);
    else
        text = 'NaN';
    end
else
    text = char(string(value));
end
text = strrep(text, '|', '/');
end

function md = missing_files_markdown_local(missing_files)
if isempty(missing_files)
    md = '_None._';
    return;
end
lines = cell(numel(missing_files), 1);
for idx = 1:numel(missing_files)
    lines{idx} = ['- ' missing_files{idx}];
end
md = strjoin(lines, newline);
end

function write_text_local(path, text)
fid = fopen(path, 'w');
if fid < 0
    error('write_step11_1_final_docs:OpenFailed', 'Could not open %s.', path);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '%s', text);
clear cleanup;
end

function text = join_lines_local(lines)
text = strjoin(lines, newline);
end
