function doc_paths = write_step11_6_docs(result_dir, keypoints, stage1_summary, stage2_summary, stage3_summary, stage4_summary, cache_metadata)
%WRITE_STEP11_6_DOCS Write Step11.6 Markdown reports.

doc_names = { ...
    '00_STEP11_6_ONE_PAGE_SUMMARY.md'; ...
    '01_THEORY_ROTATION_EQUIVALENCE.md'; ...
    '02_CACHE_ALGORITHM_FLOW.md'; ...
    '03_MANIFOLD_EQUIVALENCE_RESULTS.md'; ...
    '04_SEARCH_CONSISTENCY_RESULTS.md'; ...
    '05_RUNTIME_AND_MEMORY_RESULTS.md'; ...
    '06_LIMITATIONS_AND_USAGE_BOUNDARY.md'; ...
    '07_THESIS_WRITING_TEXT.md'};
doc_paths = cell(numel(doc_names), 1);
for idx = 1:numel(doc_names)
    doc_paths{idx} = fullfile(result_dir, doc_names{idx});
end

write_text_local(doc_paths{1}, one_page_text_local(keypoints));
write_text_local(doc_paths{2}, theory_text_local());
write_text_local(doc_paths{3}, flow_text_local());
write_text_local(doc_paths{4}, manifold_text_local(stage1_summary));
write_text_local(doc_paths{5}, search_text_local(stage2_summary));
write_text_local(doc_paths{6}, runtime_text_local(stage3_summary, cache_metadata));
write_text_local(doc_paths{7}, limitations_text_local(stage4_summary));
write_text_local(doc_paths{8}, thesis_text_local());
end

function txt = one_page_text_local(k)
txt = sprintf(['# Step11.6 One-Page Summary\n\n', ...
    'Method name: Shared-Center Rotatable Beamspace Manifold Cache for Cylindrical-Array Beamspace ML.\n\n', ...
    'Positioning: Step11.5 C05 reduces candidate count; Step11.6 keeps the same ML score and candidates but accelerates reusable manifold construction through exact canonical cache lookup.\n\n', ...
    'Fixed assumptions: shared-center canonical local order, W=greedy_combined_B7 on canonical order, exact grid lookup, no interpolation, no truth-assisted search center or policy decision.\n\n', ...
    'Key metrics: manifold_pass=%d, search_pass=%d, cross_center_pass=%d, runtime_manifold_pass=%d, runtime_search_pass=%d, overall_pass=%d.\n\n', ...
    'Max errors: max_rel_a=%.3g, max_rel_G=%.3g, max_relative_score_diff=%.3g, cache_miss_count=%.0f.\n\n', ...
    'Final recommendation: `%s`.\n'], ...
    k.manifold_equivalence_pass_flag, k.search_consistency_pass_flag, k.cross_center_reuse_pass_flag, ...
    k.runtime_manifold_pass_flag, k.runtime_search_pass_flag, k.step11_6_overall_pass_flag, ...
    k.max_rel_a_error, k.max_rel_G_error, k.max_relative_score_diff, k.cache_miss_count, k.step11_6_recommendation);
end

function txt = theory_text_local()
txt = ['# Rotation Equivalence Theory', newline, newline, ...
    'Let the actual shared-center local subarray be `r_m(theta_c)=R_z(theta_c) r''_m` and the target direction be `u(theta_c+delta, el)=R_z(theta_c)u(delta, el)`. Then', newline, newline, ...
    '`r_m(theta_c)^T u(theta_c+delta, el) = (R_z r''_m)^T(R_z u(delta, el)) = r''_m^T u(delta, el)`.', newline, newline, ...
    'Therefore the element-domain steering vector at an actual center is numerically equal to the canonical steering vector at local delta azimuth when the 65-column by 32-layer order is the same.', newline, newline, ...
    'The cached object stores `a_cache(delta,el)` implicitly through `G_cache(delta,el)=W''a_cache(delta,el)`. It is valid only when W corresponds to the canonical local order. If W encodes an absolute global-coordinate ordering, the array data and W must be rotated/reordered together and verified again.', newline];
end

function txt = flow_text_local()
txt = ['# Cache Algorithm Flow', newline, newline, ...
    'Offline build:', newline, ...
    '1. Build canonical shared-center geometry at the nearest 0 deg physical column.', newline, ...
    '2. Build Step11.2 `greedy_combined_B7` W on canonical local order.', newline, ...
    '3. Precompute `G(delta_az,el)=W''A_cyl(delta_az,el)` on the union exact grid needed by Stage1, coarse search, and local refine.', newline, newline, ...
    'Online exact lookup:', newline, ...
    '1. Snap the requested center to the actual column center.', newline, ...
    '2. Reorder the actual working subarray to canonical local order.', newline, ...
    '3. Convert global azimuth grid to `delta_az=az-actual_center_az`.', newline, ...
    '4. Exact lookup cached G. Missing grid points are recorded and may fall back to direct precompute; no interpolation is used by default.', newline, newline, ...
    'Pseudocode:', newline, newline, ...
    '```matlab', newline, ...
    'cache = build_step11_6_canonical_beamspace_cache(W, geom0, delta_grid, el_grid, lambda);', newline, ...
    'G = lookup_step11_6_beamspace_cache(cache, az_grid, el_values, ''CenterAzDeg'', center);', newline, ...
    'score = controlled_pair2d_dml_score(Z, G); % unchanged Step11.3 score path', newline, ...
    '```', newline];
end

function txt = manifold_text_local(T)
txt = sprintf(['# Stage1 Manifold Equivalence Results\n\n', ...
    'Trials: %.0f. Tested centers: %.0f.\n\n', ...
    'Max relative a error: %.3g.\n\n', ...
    'Max relative G error: %.3g.\n\n', ...
    'Max phase-aligned relative a error: %.3g.\n\n', ...
    'Max phase-aligned relative G error: %.3g.\n\n', ...
    'Pass flag: %.0f.\n\n', ...
    'Recommendation: `%s`.\n'], ...
    T.num_trials(1), T.num_tested_centers(1), T.max_rel_a_error(1), T.max_rel_G_error(1), ...
    T.max_phase_aligned_rel_a_error(1), T.max_phase_aligned_rel_G_error(1), ...
    T.manifold_equivalence_pass_flag(1), text_field_local(T, 'recommendation'));
end

function txt = search_text_local(T)
txt = sprintf(['# Stage2 Search Consistency Results\n\n', ...
    'Trials: %.0f.\n\n', ...
    'Same estimate rate: %.6f.\n\n', ...
    'Same policy rate: %.6f.\n\n', ...
    'Max relative score difference: %.3g.\n\n', ...
    'Cache miss count: %.0f.\n\n', ...
    'Success match rate: %.6f.\n\n', ...
    'TopK miss match rate: %.6f.\n\n', ...
    'Boundary hit match rate: %.6f.\n\n', ...
    'Pass flag: %.0f.\n'], ...
    T.num_trials(1), T.same_estimate_rate(1), T.same_policy_rate(1), T.max_relative_score_diff(1), ...
    T.cache_miss_count(1), T.success_match_rate(1), T.topK_miss_match_rate(1), ...
    T.boundary_hit_match_rate(1), T.search_consistency_pass_flag(1));
end

function txt = runtime_text_local(T, cache_metadata)
txt = sprintf(['# Stage3 Runtime And Memory Results\n\n', ...
    'Cache build once time: %.6f s.\n\n', ...
    'Cache memory: %.6f MB.\n\n', ...
    'Median manifold time reduction: %.6f, IQR %.6f.\n\n', ...
    'Median search time reduction: %.6f, IQR %.6f.\n\n', ...
    'Runtime manifold pass: %.0f.\n\n', ...
    'Runtime search pass: %.0f.\n\n', ...
    'MATLAB caveat: total search runtime includes DML score loops, whitening, function calls, and table overhead; a clear manifold-build speedup may not always appear as a large end-to-end runtime gain in MATLAB.\n'], ...
    numeric_value_local(cache_metadata, 'cache_build_time_sec', T.cache_build_once_time_sec(1)), ...
    numeric_value_local(cache_metadata, 'cache_memory_MB', T.cache_memory_MB(1)), ...
    T.median_manifold_time_reduction_ratio(1), T.iqr_manifold_time_reduction_ratio(1), ...
    T.median_search_time_reduction_ratio(1), T.iqr_search_time_reduction_ratio(1), ...
    T.runtime_manifold_pass_flag(1), T.runtime_search_pass_flag(1));
end

function txt = limitations_text_local(T)
txt = sprintf(['# Limitations And Usage Boundary\n\n', ...
    'This is not a new ML model and does not modify the controlled pair2d DML score.\n\n', ...
    'It does not modify Step11.5 C05 parameters, topK/window rules, or policy decisions.\n\n', ...
    'Default lookup mode is exact grid lookup only. Non-grid interpolation is future work and is not part of the passing result.\n\n', ...
    'The cache is valid only under shared-center canonical local order. Each actual working subarray must be reordered to the same 65-column by 32-layer order before using the cache.\n\n', ...
    'W must match the canonical local order. If W carries absolute global-coordinate assumptions, rotate/reorder W and validate again.\n\n', ...
    'If a cache miss occurs, the implementation records it and falls back to direct precompute; no silent interpolation is allowed.\n\n', ...
    'No arbitrary full-field claim is made. Stage4 tested centers=%.0f, passed centers=%.0f, cross-center pass=%.0f.\n'], ...
    T.num_tested_centers(1), T.num_passed_centers(1), T.cross_center_reuse_pass_flag(1));
end

function txt = thesis_text_local()
txt = ['# Thesis Writing Text', newline, newline, ...
    'Case 1, overall pass = 1 and runtime search pass = 1:', newline, ...
    '本文进一步利用全息凝视圆柱阵 shared-center 局部工作子阵的旋转等价性，提出一种 canonical beamspace manifold cache 方法。该方法将不同扇区中心下的局部导向矢量统一映射到 canonical Delta-az 坐标中，预先存储 G = W''A_cyl 的波束域流形模板，并在在线 controlled pair2d beamspace ML 搜索中进行 exact-grid lookup。实验表明，该缓存方法与 direct steering precompute 在流形、score、估计结果和 policy 分支上保持数值一致，同时降低 manifold 构造和总搜索运行时间，可作为 Step11.5 C05 自适应搜索的工程加速模块。', newline, newline, ...
    'Case 2, overall pass = 1 and runtime search pass = 0:', newline, ...
    '本文进一步验证了 shared-center 圆柱阵局部流形的 canonical cache 复用方法。实验表明，该方法在多个中心方位下与 direct precompute 保持流形和搜索结果一致，并显著降低 manifold 构造成本；但在 MATLAB 原型中，总搜索时间仍主要受后续 DML score 计算和函数调度开销限制。因此本文将该方法作为 FPGA/SoC 友好的 manifold 构造加速模块，而不单独声称 MATLAB 总 runtime 显著下降。', newline, newline, ...
    'Case 3, overall pass = 0:', newline, ...
    '本文尝试利用 shared-center 旋转等价性构造 canonical beamspace manifold cache，但在当前 W、局部子阵顺序或中心映射下未能完全保持 direct precompute 的数值一致性。因此本文暂不将该 cache 作为默认实现，而将其作为圆柱阵工程部署中的未来优化方向保留。', newline];
end

function write_text_local(path, text)
fid = fopen(path, 'w', 'n', 'UTF-8');
if fid < 0
    error('write_step11_6_docs:OpenFailed', 'Could not open %s.', path);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '%s', text);
clear cleanup;
end

function value = numeric_value_local(T, field, fallback)
value = fallback;
if istable(T) && ismember(field, T.Properties.VariableNames) && height(T) >= 1
    value = T.(field)(1);
elseif isstruct(T) && isfield(T, field)
    value = T.(field);
end
if ~(isnumeric(value) && isscalar(value) && isfinite(value))
    value = fallback;
end
end

function value = text_field_local(T, field)
raw = T.(field);
if iscell(raw)
    value = raw{1};
elseif isstring(raw)
    value = char(raw(1));
elseif ischar(raw)
    value = raw;
else
    value = char(string(raw(1)));
end
end
