set script_dir [file dirname [file normalize [info script]]]
set timing_dir [file normalize $script_dir]
puts "Step14.3b timing reports are generated by run_reference_bd_strategy_sweep.tcl."
puts "Run from Step14 directory:"
puts "  powershell -ExecutionPolicy Bypass -File vivado/reference_bd_timing/run_reference_bd_strategy_sweep.ps1"
