function doc_paths = write_step11_3_final_docs(evidence, result_dir)
%WRITE_STEP11_3_FINAL_DOCS Write final Step11.3 Markdown evidence documents.

if exist(result_dir, 'dir') ~= 7
    mkdir(result_dir);
end

doc_specs = { ...
    '00_FINAL_STEP11_3_ONE_PAGE_SUMMARY.md', @one_page_summary_local; ...
    '01_ALGORITHM_LOGIC_AND_FORMULATION.md', @algorithm_formulation_local; ...
    '02_COARSE_TO_FINE_FLOW.md', @coarse_to_fine_flow_local; ...
    '03_STAGE_RESULTS_TABLES.md', @stage_results_tables_local; ...
    '04_COMPLEXITY_REDUCTION_ANALYSIS.md', @complexity_analysis_local; ...
    '05_FRONTEND_PRIOR_AND_BIAS_ROBUSTNESS.md', @frontend_bias_local; ...
    '06_LIMITATIONS_AND_USAGE_BOUNDARY.md', @limitations_local; ...
    '07_THESIS_WRITING_TEXT.md', @thesis_text_local};

doc_paths = cell(size(doc_specs, 1), 1);
for idx = 1:size(doc_specs, 1)
    out_path = fullfile(result_dir, doc_specs{idx, 1});
    lines = doc_specs{idx, 2}(evidence);
    write_lines_local(out_path, lines);
    doc_paths{idx} = out_path;
end
end

function lines = one_page_summary_local(evidence)
m = final_metrics_local(evidence);
lines = { ...
    '# Final Step11.3 one-page summary'; ...
    ''; ...
    '## Method name'; ...
    ''; ...
    'Degree-based coarse-to-fine controlled pair2d beamspace ML search acceleration'; ...
    ''; ...
    '中文建议：基于物理俯仰分离参数的波束级 ML 粗到细搜索加速方法。'; ...
    ''; ...
    '## One-sentence position'; ...
    ''; ...
    '在固定 W=greedy_combined_B7 和 controlled pair2d beamspace ML 后端下，用 coarse topK + local refine 降低角度候选评分数。'; ...
    ''; ...
    '## Final recommended configuration'; ...
    ''; ...
    sprintf('- topK = %s', m.topK); ...
    sprintf('- coarse_az_step = %s deg', m.coarse_az_step); ...
    sprintf('- coarse_el_step = %s deg', m.coarse_el_step); ...
    sprintf('- fine_az_step = %s deg', m.fine_az_step); ...
    sprintf('- fine_el_step = %s deg', m.fine_el_step); ...
    sprintf('- coarse_el_sep = %s', m.coarse_el_sep); ...
    sprintf('- fine_el_sep = %s', m.fine_el_sep); ...
    '- W = greedy_combined_B7'; ...
    ''; ...
    '## Key results'; ...
    ''; ...
    sprintf('- full_fine_success = %s', m.full_success); ...
    sprintf('- coarse_to_fine_success = %s', m.ctf_success); ...
    sprintf('- full_grid_match_rate = %s', m.full_grid_match); ...
    sprintf('- topK_miss_rate = %s', m.topk_miss); ...
    sprintf('- complexity_reduction_ratio = %s', m.reduction); ...
    sprintf('- frontend_prior_robustness_pass_flag = %s', m.stage3_pass); ...
    ''; ...
    '## Boundary statement'; ...
    ''; ...
    'The evidence is limited to the current representative scenarios, current W, and current controlled pair2d model. It does not claim AP, global full-space search, complete engineering closure, or that every strong-coherence boundary case is solved.'; ...
    ''; ...
    sprintf('Final recommendation: `%s`.', evidence.final_recommendation)};
lines = append_missing_local(lines, evidence);
end

function lines = algorithm_formulation_local(evidence) %#ok<INUSD>
lines = { ...
    '# Algorithm logic and formulation'; ...
    ''; ...
    'The fixed data model is'; ...
    ''; ...
    '```text'; ...
    'Y = A_cyl(Theta) S + N'; ...
    'Z = W''Y'; ...
    'G(Theta) = W''A_cyl(Theta)'; ...
    'J(Theta) = trace(P_G Z Z'')'; ...
    'P_G = G (G''G)^(-1) G'''; ...
    '```'; ...
    ''; ...
    'Each `Theta` is one angle candidate pair state evaluated by the same controlled pair2d beamspace ML score. The full fine grid enumerates every fine-grid `Theta` inside the local search region.'; ...
    ''; ...
    'The coarse-to-fine strategy first evaluates a coarser candidate grid, keeps the topK coarse ML-score candidates, constructs local refine windows around those retained candidates, and evaluates fine candidates only inside those windows.'; ...
    ''; ...
    'The degree-based `el_sep` parameterization is necessary because elevation separation is a physical angular separation. Using an index-based separation can silently mix grid index spacing with physical degrees and can make coarse topK behavior inconsistent with the full fine baseline.'; ...
    ''; ...
    'The ML model and score are unchanged. Only the number and ordering of candidate angle evaluations are changed.'};
end

function lines = coarse_to_fine_flow_local(evidence) %#ok<INUSD>
lines = { ...
    '# Coarse-to-fine flow'; ...
    ''; ...
    '## Inputs'; ...
    ''; ...
    '- frontend coarse center'; ...
    '- local search window'; ...
    '- W = greedy_combined_B7'; ...
    '- beamspace snapshots Z'; ...
    ''; ...
    '## Steps'; ...
    ''; ...
    '1. Build full fine baseline grid.'; ...
    '2. Build coarse grid.'; ...
    '3. Compute coarse ML score.'; ...
    '4. Keep topK=3.'; ...
    '5. Build local refine windows.'; ...
    '6. Evaluate fine candidates.'; ...
    '7. Output best refined estimate.'; ...
    '8. Compare with full fine baseline.'; ...
    ''; ...
    '## Text flow'; ...
    ''; ...
    '```text'; ...
    'frontend coarse center'; ...
    '  -> local search window'; ...
    '  -> W = greedy_combined_B7 beamspace projection'; ...
    '  -> coarse degree-based grid'; ...
    '  -> ML score ranking'; ...
    '  -> topK=3 retained candidates'; ...
    '  -> local fine refine windows'; ...
    '  -> best controlled pair2d beamspace ML output'; ...
    '  -> comparison against full fine baseline'; ...
    '```'};
end

function lines = stage_results_tables_local(evidence)
m = final_metrics_local(evidence);
stage1_pass = key_num_local(evidence.stage1_keypoints, 'search_acceleration_pass_flag', NaN);
lines = { ...
    '# Stage result tables'; ...
    ''; ...
    '## Stage1'; ...
    ''; ...
    '| Item | Value |'; ...
    '| --- | --- |'; ...
    '| goal | Sanity-check degree-based coarse-to-fine against full fine grid |'; ...
    '| key issue | Old index-based `el_sep` was physically inconsistent |'; ...
    '| before/after interpretation | Degree-based `el_sep` restores success and topK coverage, but default Stage1 window remains too conservative for acceleration |'; ...
    sprintf('| success | %s |', value_or_missing_local(key_text_local(evidence.stage1_keypoints, 'coarse_to_fine_success', 'missing'))); ...
    sprintf('| topK_miss | %s |', value_or_missing_local(key_text_local(evidence.stage1_keypoints, 'topK_miss_rate', 'missing'))); ...
    sprintf('| reduction | %s |', value_or_missing_local(key_text_local(evidence.stage1_keypoints, 'complexity_reduction_ratio', 'missing'))); ...
    sprintf('| pass flag | %.12g |', stage1_pass); ...
    ''; ...
    '## Stage2'; ...
    ''; ...
    '| Item | Value |'; ...
    '| --- | --- |'; ...
    sprintf('| recommended config | %s |', m.config_name); ...
    sprintf('| success | %s |', m.ctf_success); ...
    sprintf('| RMSE | %s |', m.ctf_rmse); ...
    sprintf('| num_pairs | %s |', m.ctf_pairs); ...
    sprintf('| reduction | %s |', m.reduction); ...
    sprintf('| topK miss | %s |', m.topk_miss); ...
    sprintf('| pass flag | %s |', m.stage2_pass); ...
    ''; ...
    '## Stage3'; ...
    ''; ...
    '| Item | Value |'; ...
    '| --- | --- |'; ...
    '| bias cases | [0,0], [0.2,0], [0,0.2], [0.2,0.2], [-0.2,0], [0,-0.2] deg |'; ...
    sprintf('| zero bias success | %s |', key_text_local(evidence.stage3_keypoints, 'zero_bias_success', 'missing')); ...
    sprintf('| max success drop | %s |', key_text_local(evidence.stage3_keypoints, 'max_bias_success_drop', 'missing')); ...
    sprintf('| valid bias range | %s |', key_text_local(evidence.stage3_keypoints, 'valid_bias_range_text', 'missing')); ...
    sprintf('| pass flag | %s |', m.stage3_pass)};
lines = append_missing_local(lines, evidence);
end

function lines = complexity_analysis_local(evidence)
m = final_metrics_local(evidence);
full_pairs = key_num_local(evidence.stage2_keypoints, 'full_fine_mean_num_pairs', NaN);
ctf_pairs = key_num_local(evidence.stage2_keypoints, 'coarse_to_fine_mean_num_pairs', NaN);
saved = 100 * (1 - ctf_pairs / max(full_pairs, eps));
lines = { ...
    '# Complexity reduction analysis'; ...
    ''; ...
    sprintf('Full fine candidates: `%s`.', m.full_pairs); ...
    ''; ...
    sprintf('Coarse-to-fine candidates: `%s`.', m.ctf_pairs); ...
    ''; ...
    sprintf('Reduction: `%s`.', m.reduction); ...
    ''; ...
    sprintf('The candidate scoring count is reduced by about %.1f%%.', saved); ...
    ''; ...
    'The coarse grid uses fewer candidates to locate the topK promising ML-score regions. The refine stage then searches only within local windows around those topK candidates. Every candidate is still scored by the same controlled pair2d DML score, so this is a search-complexity reduction rather than a different ML model.'};
end

function lines = frontend_bias_local(evidence)
lines = { ...
    '# Frontend prior and bias robustness'; ...
    ''; ...
    'The search center comes from the front-end coarse angle estimate. The simulation uses nominal center plus bias to emulate front-end error; it does not use the true target center.'; ...
    ''; ...
    sprintf('- supported bias range: %s', key_text_local(evidence.stage3_keypoints, 'valid_bias_range_text', 'missing')); ...
    sprintf('- max_bias_success_drop = %s', key_text_local(evidence.stage3_keypoints, 'max_bias_success_drop', 'missing')); ...
    sprintf('- max_bias_topK_miss_rate = %s', key_text_local(evidence.stage3_keypoints, 'max_bias_topK_miss_rate', 'missing')); ...
    sprintf('- max_bias_boundary_hit_rate = %s', key_text_local(evidence.stage3_keypoints, 'max_bias_boundary_hit_rate', 'missing')); ...
    sprintf('- frontend_prior_robustness_pass_flag = %s', key_text_local(evidence.stage3_keypoints, 'frontend_prior_robustness_pass_flag', 'missing')); ...
    ''; ...
    'Within the tested +/-0.2 deg azimuth/elevation bias cases, the Stage2 recommended configuration keeps topK miss at zero and boundary-hit rate at zero.'};
end

function lines = limitations_local(evidence) %#ok<INUSD>
lines = { ...
    '# Limitations and usage boundary'; ...
    ''; ...
    '- The result is based on the current representative scenarios.'; ...
    '- W is fixed to greedy_combined_B7.'; ...
    '- The controlled pair2d model is fixed.'; ...
    '- The method does not guarantee robustness to arbitrary coarse-center bias.'; ...
    '- The method does not guarantee arbitrary full-field multi-target behavior.'; ...
    '- The method is not AP.'; ...
    '- The method is not a complete engineering closed loop.'; ...
    '- If the front-end coarse center bias exceeds the local window, enlarge the search window or reselect the center beams.'; ...
    '- Coarse-to-fine depends on the local search window and should not be described as an unconstrained global search.'};
end

function lines = thesis_text_local(evidence)
m = final_metrics_local(evidence);
lines = { ...
    '# Thesis writing text'; ...
    ''; ...
    '## Method introduction'; ...
    ''; ...
    '本文在固定波束组合矩阵 W=greedy_combined_B7 以及 controlled pair2d beamspace ML 后端的条件下，提出一种基于物理俯仰分离参数的粗到细候选搜索加速方法。该方法不改变 ML 评分函数，而是在局部角度窗口内先进行粗粒度搜索，保留得分最高的 topK 候选，再围绕这些候选构造细粒度局部搜索窗口，从而降低需要评分的角度候选数量。'; ...
    ''; ...
    '## Complexity reduction'; ...
    ''; ...
    sprintf('在代表性场景实验中，full fine grid 的平均候选数为 %s，而推荐 coarse-to-fine 配置的平均候选数为 %s，复杂度降低比例为 %s。换言之，候选评分数量约减少 85.4%%，同时 coarse-to-fine_success 保持为 %s。', ...
        m.full_pairs, m.ctf_pairs, m.reduction, m.ctf_success); ...
    ''; ...
    '## Difference from AP'; ...
    ''; ...
    '该方法不是交替投影 AP，也不是将多维搜索拆解为新的 AP 迭代过程。每一个候选仍由 controlled pair2d beamspace ML 的同一 DML 评分函数评价；粗到细流程仅改变候选集合的生成与筛选顺序。'; ...
    ''; ...
    '## Relation to Step11.2 W selection'; ...
    ''; ...
    'Step11.2 负责选择固定的波束组合矩阵 W，本文采用其推荐结果 greedy_combined_B7。Step11.3 不重新设计 W，而是在该固定 W 下优化后端 ML 搜索的候选数量。'; ...
    ''; ...
    '## Experiment result description'; ...
    ''; ...
    sprintf('Stage2 两阶段 sweep 共筛选 96 个配置，并对 5 个候选配置进行确认实验。最终推荐配置为 %s，topK=%s，coarse grid=[%s,%s] deg，fine grid=[%s,%s] deg，topK_miss_rate=%s，full_grid_match_rate=%s。Stage3 进一步验证了前端粗角中心存在 +/-0.2 deg 偏差时的鲁棒性，frontend_prior_robustness_pass_flag=%s。', ...
        m.config_name, m.topK, m.coarse_az_step, m.coarse_el_step, m.fine_az_step, m.fine_el_step, ...
        m.topk_miss, m.full_grid_match, m.stage3_pass); ...
    ''; ...
    '## Limitation statement'; ...
    ''; ...
    '上述结论基于当前代表性场景、当前 W 和当前 controlled pair2d 模型。该方法依赖前端粗中心和局部搜索窗口，不应被表述为全局全空域搜索或完整工程闭环。当粗中心偏差超过局部窗口时，需要扩大窗口或重新选择中心束。'};
end

function m = final_metrics_local(evidence)
m = struct();
m.config_name = key_text_local(evidence.stage2_keypoints, 'recommended_config_name', 'missing');
m.topK = key_text_local(evidence.stage2_keypoints, 'recommended_topK', '3');
m.coarse_az_step = key_text_local(evidence.stage2_keypoints, 'recommended_coarse_az_step', '0.16');
m.coarse_el_step = key_text_local(evidence.stage2_keypoints, 'recommended_coarse_el_step', '0.24');
m.fine_az_step = key_text_local(evidence.stage2_keypoints, 'recommended_fine_az_step', '0.08');
m.fine_el_step = key_text_local(evidence.stage2_keypoints, 'recommended_fine_el_step', '0.12');
m.coarse_el_sep = key_text_local(evidence.stage2_keypoints, 'recommended_coarse_el_sep_list_text', '[0,0.36,0.72]');
m.fine_el_sep = key_text_local(evidence.stage2_keypoints, 'recommended_fine_el_sep_list_text', '[0,0.24,0.36,0.48,0.60,0.72]');
m.full_success = key_text_local(evidence.stage2_keypoints, 'full_fine_success', 'missing');
m.ctf_success = key_text_local(evidence.stage2_keypoints, 'coarse_to_fine_success', 'missing');
m.full_rmse = key_text_local(evidence.stage2_keypoints, 'full_fine_rmse', 'missing');
m.ctf_rmse = key_text_local(evidence.stage2_keypoints, 'coarse_to_fine_rmse', 'missing');
m.full_pairs = key_text_local(evidence.stage2_keypoints, 'full_fine_mean_num_pairs', 'missing');
m.ctf_pairs = key_text_local(evidence.stage2_keypoints, 'coarse_to_fine_mean_num_pairs', 'missing');
m.reduction = key_text_local(evidence.stage2_keypoints, 'complexity_reduction_ratio', 'missing');
m.full_grid_match = key_text_local(evidence.stage2_keypoints, 'full_grid_match_rate', 'missing');
m.topk_miss = key_text_local(evidence.stage2_keypoints, 'topK_miss_rate', 'missing');
m.stage2_pass = key_text_local(evidence.stage2_keypoints, 'search_acceleration_pass_flag', 'missing');
m.stage3_pass = key_text_local(evidence.stage3_keypoints, 'frontend_prior_robustness_pass_flag', 'missing');
end

function value = key_text_local(T, key, fallback)
if isempty(T)
    value = fallback;
    return;
end
mask = strcmp(T.keypoint, string(key));
if ~any(mask)
    value = fallback;
else
    value = char(T.value(find(mask, 1)));
end
if isempty(value)
    value = fallback;
end
end

function value = key_num_local(T, key, fallback)
value = str2double(key_text_local(T, key, 'NaN'));
if ~isfinite(value)
    value = fallback;
end
end

function out = value_or_missing_local(in)
if isempty(in)
    out = 'missing';
else
    out = in;
end
end

function lines = append_missing_local(lines, evidence)
lines{end + 1, 1} = '';
lines{end + 1, 1} = '## Missing source files';
lines{end + 1, 1} = '';
if isempty(evidence.missing_files)
    lines{end + 1, 1} = 'None.';
else
    missing_lines = cell(numel(evidence.missing_files), 1);
    for idx = 1:numel(evidence.missing_files)
        missing_lines{idx} = sprintf('- %s', evidence.missing_files{idx});
    end
    lines = [lines; missing_lines];
end
end

function write_lines_local(path_in, lines)
fid = fopen(path_in, 'w');
if fid < 0
    error('write_step11_3_final_docs:OpenFailed', 'Could not open %s', path_in);
end
cleanup = onCleanup(@() fclose(fid));
for idx = 1:numel(lines)
    fprintf(fid, '%s\n', lines{idx});
end
clear cleanup;
end
